# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.test.testapiresource.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2


class TestApiResourceCommandControllerStub(object):
    """test-api-resource command controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/create',
                request_serializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/update',
                request_serializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
                _registered_method=True)
        self.delete = channel.unary_unary(
                '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/delete',
                request_serializer=cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2.ApiResourceId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
                _registered_method=True)


class TestApiResourceCommandControllerServicer(object):
    """test-api-resource command controller
    """

    def create(self, request, context):
        """create a test-api-resource resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """update an existing test-api-resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """delete a test-api-resource that was previously created
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestApiResourceCommandControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2.ApiResourceId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestApiResourceCommandController(object):
    """test-api-resource command controller
    """

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/create',
            cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
            cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/update',
            cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.SerializeToString,
            cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.test.testapiresource.v1.TestApiResourceCommandController/delete',
            cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2.ApiResourceId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_test_dot_testapiresource_dot_v1_dot_api__pb2.TestApiResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
