# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/cloudflare/cloudflarekvnamespace/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/cloudflare/cloudflarekvnamespace/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGproject/planton/provider/cloudflare/cloudflarekvnamespace/v1/spec.proto\x12<project.planton.provider.cloudflare.cloudflarekvnamespace.v1\x1a\x1b\x62uf/validate/validate.proto\"\xa4\x01\n\x19\x43loudflareKvNamespaceSpec\x12\x31\n\x0enamespace_name\x18\x01 \x01(\tB\n\xbaH\x07r\x02\x18@\xc8\x01\x01R\rnamespaceName\x12(\n\x0bttl_seconds\x18\x02 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\nttlSeconds\x12*\n\x0b\x64\x65scription\x18\x03 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x02R\x0b\x64\x65scriptionB\xe4\x02\n@com.project.planton.provider.cloudflare.cloudflarekvnamespace.v1B\tSpecProtoP\x01\xa2\x02\x05PPPCC\xaa\x02<Project.Planton.Provider.Cloudflare.Cloudflarekvnamespace.V1\xca\x02<Project\\Planton\\Provider\\Cloudflare\\Cloudflarekvnamespace\\V1\xe2\x02HProject\\Planton\\Provider\\Cloudflare\\Cloudflarekvnamespace\\V1\\GPBMetadata\xea\x02\x41Project::Planton::Provider::Cloudflare::Cloudflarekvnamespace::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.cloudflare.cloudflarekvnamespace.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n@com.project.planton.provider.cloudflare.cloudflarekvnamespace.v1B\tSpecProtoP\001\242\002\005PPPCC\252\002<Project.Planton.Provider.Cloudflare.Cloudflarekvnamespace.V1\312\002<Project\\Planton\\Provider\\Cloudflare\\Cloudflarekvnamespace\\V1\342\002HProject\\Planton\\Provider\\Cloudflare\\Cloudflarekvnamespace\\V1\\GPBMetadata\352\002AProject::Planton::Provider::Cloudflare::Cloudflarekvnamespace::V1'
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['namespace_name']._loaded_options = None
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['namespace_name']._serialized_options = b'\272H\007r\002\030@\310\001\001'
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['ttl_seconds']._loaded_options = None
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['ttl_seconds']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['description']._loaded_options = None
  _globals['_CLOUDFLAREKVNAMESPACESPEC'].fields_by_name['description']._serialized_options = b'\272H\005r\003\030\200\002'
  _globals['_CLOUDFLAREKVNAMESPACESPEC']._serialized_start=167
  _globals['_CLOUDFLAREKVNAMESPACESPEC']._serialized_end=331
# @@protoc_insertion_point(module_scope)
