# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/cloudresource/v1/provider/kubernetes/workload/microservicekubernetes/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/cloudresource/v1/provider/kubernetes/workload/microservicekubernetes/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetes import io_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_kubernetes_dot_workload_dot_microservicekubernetes_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nlcloud/planton/apis/infrahub/cloudresource/v1/provider/kubernetes/workload/microservicekubernetes/query.proto\x12`cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetes\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1aicloud/planton/apis/infrahub/cloudresource/v1/provider/kubernetes/workload/microservicekubernetes/io.proto2\xba\x03\n%MicroserviceKubernetesQueryController\x12\x8a\x03\n\x0cgetEnvVarMap\x12\x89\x01.cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetes.GetMicroserviceKubernetesEnvVarMapInput\x1a\x81\x01.cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetes.MicroserviceKubernetesEnvVarMap\"j\xc2\xb8\x18\x66\x08\x05\x10.\"\x1amicroservice_kubernetes_id*Dunauthorized to get environment variables of microservice-kubernetes\x1a\x04\xa0\xff+.B\xa2\x04\ndcom.cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetesB\nQueryProtoP\x01\xa2\x02\nCPAICVPKWM\xaa\x02`Cloud.Planton.Apis.Infrahub.Cloudresource.V1.Provider.Kubernetes.Workload.Microservicekubernetes\xca\x02`Cloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Kubernetes\\Workload\\Microservicekubernetes\xe2\x02lCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Kubernetes\\Workload\\Microservicekubernetes\\GPBMetadata\xea\x02iCloud::Planton::Apis::Infrahub::Cloudresource::V1::Provider::Kubernetes::Workload::Microservicekubernetesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetes.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\ndcom.cloud.planton.apis.infrahub.cloudresource.v1.provider.kubernetes.workload.microservicekubernetesB\nQueryProtoP\001\242\002\nCPAICVPKWM\252\002`Cloud.Planton.Apis.Infrahub.Cloudresource.V1.Provider.Kubernetes.Workload.Microservicekubernetes\312\002`Cloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Kubernetes\\Workload\\Microservicekubernetes\342\002lCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Kubernetes\\Workload\\Microservicekubernetes\\GPBMetadata\352\002iCloud::Planton::Apis::Infrahub::Cloudresource::V1::Provider::Kubernetes::Workload::Microservicekubernetes'
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER']._loaded_options = None
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER']._serialized_options = b'\240\377+.'
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER'].methods_by_name['getEnvVarMap']._loaded_options = None
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER'].methods_by_name['getEnvVarMap']._serialized_options = b'\302\270\030f\010\005\020.\"\032microservice_kubernetes_id*Dunauthorized to get environment variables of microservice-kubernetes'
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER']._serialized_start=459
  _globals['_MICROSERVICEKUBERNETESQUERYCONTROLLER']._serialized_end=901
# @@protoc_insertion_point(module_scope)
