# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/commons/english/acronym.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/commons/english/acronym.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0cloud/planton/apis/commons/english/acronym.proto\x12\"cloud.planton.apis.commons.english\"H\n\x0e\x45nglishAcronym\"6\n\x12\x45nglishAcronymEnum\x12\x0f\n\x0bunspecified\x10\x00\x12\x06\n\x02NW\x10\x01\x12\x07\n\x03RPC\x10\x02\x42\xe4\x01\n&com.cloud.planton.apis.commons.englishB\x0c\x41\x63ronymProtoP\x01\xa2\x02\x05\x43PACE\xaa\x02\"Cloud.Planton.Apis.Commons.English\xca\x02\"Cloud\\Planton\\Apis\\Commons\\English\xe2\x02.Cloud\\Planton\\Apis\\Commons\\English\\GPBMetadata\xea\x02&Cloud::Planton::Apis::Commons::Englishb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.commons.english.acronym_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.cloud.planton.apis.commons.englishB\014AcronymProtoP\001\242\002\005CPACE\252\002\"Cloud.Planton.Apis.Commons.English\312\002\"Cloud\\Planton\\Apis\\Commons\\English\342\002.Cloud\\Planton\\Apis\\Commons\\English\\GPBMetadata\352\002&Cloud::Planton::Apis::Commons::English'
  _globals['_ENGLISHACRONYM']._serialized_start=88
  _globals['_ENGLISHACRONYM']._serialized_end=160
  _globals['_ENGLISHACRONYM_ENGLISHACRONYMENUM']._serialized_start=106
  _globals['_ENGLISHACRONYM_ENGLISHACRONYMENUM']._serialized_end=160
# @@protoc_insertion_point(module_scope)
