from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class EnglishWord(_message.Message):
    __slots__ = ()
    class EnglishWordEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        word_unspecified: _ClassVar[EnglishWord.EnglishWordEnum]
        app: _ClassVar[EnglishWord.EnglishWordEnum]
        application: _ClassVar[EnglishWord.EnglishWordEnum]
        aws: _ClassVar[EnglishWord.EnglishWordEnum]
        azure: _ClassVar[EnglishWord.EnglishWordEnum]
        bill: _ClassVar[EnglishWord.EnglishWordEnum]
        organization: _ClassVar[EnglishWord.EnglishWordEnum]
        config: _ClassVar[EnglishWord.EnglishWordEnum]
        cpu: _ClassVar[EnglishWord.EnglishWordEnum]
        debug: _ClassVar[EnglishWord.EnglishWordEnum]
        docker: _ClassVar[EnglishWord.EnglishWordEnum]
        domain: _ClassVar[EnglishWord.EnglishWordEnum]
        email: _ClassVar[EnglishWord.EnglishWordEnum]
        endpoint: _ClassVar[EnglishWord.EnglishWordEnum]
        external: _ClassVar[EnglishWord.EnglishWordEnum]
        file: _ClassVar[EnglishWord.EnglishWordEnum]
        gcp: _ClassVar[EnglishWord.EnglishWordEnum]
        google: _ClassVar[EnglishWord.EnglishWordEnum]
        hosting: _ClassVar[EnglishWord.EnglishWordEnum]
        hostname: _ClassVar[EnglishWord.EnglishWordEnum]
        id: _ClassVar[EnglishWord.EnglishWordEnum]
        ingress: _ClassVar[EnglishWord.EnglishWordEnum]
        instances: _ClassVar[EnglishWord.EnglishWordEnum]
        internal: _ClassVar[EnglishWord.EnglishWordEnum]
        ip: _ClassVar[EnglishWord.EnglishWordEnum]
        key: _ClassVar[EnglishWord.EnglishWordEnum]
        kubeconfig: _ClassVar[EnglishWord.EnglishWordEnum]
        kubernetes: _ClassVar[EnglishWord.EnglishWordEnum]
        localhost: _ClassVar[EnglishWord.EnglishWordEnum]
        machine: _ClassVar[EnglishWord.EnglishWordEnum]
        main: _ClassVar[EnglishWord.EnglishWordEnum]
        maven: _ClassVar[EnglishWord.EnglishWordEnum]
        memory: _ClassVar[EnglishWord.EnglishWordEnum]
        microservice: _ClassVar[EnglishWord.EnglishWordEnum]
        name: _ClassVar[EnglishWord.EnglishWordEnum]
        nameservers: _ClassVar[EnglishWord.EnglishWordEnum]
        namespace: _ClassVar[EnglishWord.EnglishWordEnum]
        network: _ClassVar[EnglishWord.EnglishWordEnum]
        npm: _ClassVar[EnglishWord.EnglishWordEnum]
        number: _ClassVar[EnglishWord.EnglishWordEnum]
        org: _ClassVar[EnglishWord.EnglishWordEnum]
        parent: _ClassVar[EnglishWord.EnglishWordEnum]
        postgres: _ClassVar[EnglishWord.EnglishWordEnum]
        project: _ClassVar[EnglishWord.EnglishWordEnum]
        python: _ClassVar[EnglishWord.EnglishWordEnum]
        repo: _ClassVar[EnglishWord.EnglishWordEnum]
        review: _ClassVar[EnglishWord.EnglishWordEnum]
        server: _ClassVar[EnglishWord.EnglishWordEnum]
        servers: _ClassVar[EnglishWord.EnglishWordEnum]
        share: _ClassVar[EnglishWord.EnglishWordEnum]
        shared_services: _ClassVar[EnglishWord.EnglishWordEnum]
        spilo: _ClassVar[EnglishWord.EnglishWordEnum]
        spot: _ClassVar[EnglishWord.EnglishWordEnum]
        stunnel: _ClassVar[EnglishWord.EnglishWordEnum]
        team: _ClassVar[EnglishWord.EnglishWordEnum]
        type: _ClassVar[EnglishWord.EnglishWordEnum]
        username: _ClassVar[EnglishWord.EnglishWordEnum]
        util: _ClassVar[EnglishWord.EnglishWordEnum]
        version: _ClassVar[EnglishWord.EnglishWordEnum]
        workload: _ClassVar[EnglishWord.EnglishWordEnum]
        url: _ClassVar[EnglishWord.EnglishWordEnum]
        env: _ClassVar[EnglishWord.EnglishWordEnum]
        kafka: _ClassVar[EnglishWord.EnglishWordEnum]
        unknown: _ClassVar[EnglishWord.EnglishWordEnum]
        resource: _ClassVar[EnglishWord.EnglishWordEnum]
        resource_id: _ClassVar[EnglishWord.EnglishWordEnum]
        resource_kind: _ClassVar[EnglishWord.EnglishWordEnum]
        environment: _ClassVar[EnglishWord.EnglishWordEnum]
    word_unspecified: EnglishWord.EnglishWordEnum
    app: EnglishWord.EnglishWordEnum
    application: EnglishWord.EnglishWordEnum
    aws: EnglishWord.EnglishWordEnum
    azure: EnglishWord.EnglishWordEnum
    bill: EnglishWord.EnglishWordEnum
    organization: EnglishWord.EnglishWordEnum
    config: EnglishWord.EnglishWordEnum
    cpu: EnglishWord.EnglishWordEnum
    debug: EnglishWord.EnglishWordEnum
    docker: EnglishWord.EnglishWordEnum
    domain: EnglishWord.EnglishWordEnum
    email: EnglishWord.EnglishWordEnum
    endpoint: EnglishWord.EnglishWordEnum
    external: EnglishWord.EnglishWordEnum
    file: EnglishWord.EnglishWordEnum
    gcp: EnglishWord.EnglishWordEnum
    google: EnglishWord.EnglishWordEnum
    hosting: EnglishWord.EnglishWordEnum
    hostname: EnglishWord.EnglishWordEnum
    id: EnglishWord.EnglishWordEnum
    ingress: EnglishWord.EnglishWordEnum
    instances: EnglishWord.EnglishWordEnum
    internal: EnglishWord.EnglishWordEnum
    ip: EnglishWord.EnglishWordEnum
    key: EnglishWord.EnglishWordEnum
    kubeconfig: EnglishWord.EnglishWordEnum
    kubernetes: EnglishWord.EnglishWordEnum
    localhost: EnglishWord.EnglishWordEnum
    machine: EnglishWord.EnglishWordEnum
    main: EnglishWord.EnglishWordEnum
    maven: EnglishWord.EnglishWordEnum
    memory: EnglishWord.EnglishWordEnum
    microservice: EnglishWord.EnglishWordEnum
    name: EnglishWord.EnglishWordEnum
    nameservers: EnglishWord.EnglishWordEnum
    namespace: EnglishWord.EnglishWordEnum
    network: EnglishWord.EnglishWordEnum
    npm: EnglishWord.EnglishWordEnum
    number: EnglishWord.EnglishWordEnum
    org: EnglishWord.EnglishWordEnum
    parent: EnglishWord.EnglishWordEnum
    postgres: EnglishWord.EnglishWordEnum
    project: EnglishWord.EnglishWordEnum
    python: EnglishWord.EnglishWordEnum
    repo: EnglishWord.EnglishWordEnum
    review: EnglishWord.EnglishWordEnum
    server: EnglishWord.EnglishWordEnum
    servers: EnglishWord.EnglishWordEnum
    share: EnglishWord.EnglishWordEnum
    shared_services: EnglishWord.EnglishWordEnum
    spilo: EnglishWord.EnglishWordEnum
    spot: EnglishWord.EnglishWordEnum
    stunnel: EnglishWord.EnglishWordEnum
    team: EnglishWord.EnglishWordEnum
    type: EnglishWord.EnglishWordEnum
    username: EnglishWord.EnglishWordEnum
    util: EnglishWord.EnglishWordEnum
    version: EnglishWord.EnglishWordEnum
    workload: EnglishWord.EnglishWordEnum
    url: EnglishWord.EnglishWordEnum
    env: EnglishWord.EnglishWordEnum
    kafka: EnglishWord.EnglishWordEnum
    unknown: EnglishWord.EnglishWordEnum
    resource: EnglishWord.EnglishWordEnum
    resource_id: EnglishWord.EnglishWordEnum
    resource_kind: EnglishWord.EnglishWordEnum
    environment: EnglishWord.EnglishWordEnum
    def __init__(self) -> None: ...
