# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/civo/civokubernetescluster/v1/stack_input.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/civo/civokubernetescluster/v1/stack_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from project.planton.provider.civo.civokubernetescluster.v1 import api_pb2 as project_dot_planton_dot_provider_dot_civo_dot_civokubernetescluster_dot_v1_dot_api__pb2
from project.planton.provider.civo import provider_pb2 as project_dot_planton_dot_provider_dot_civo_dot_provider__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHproject/planton/provider/civo/civokubernetescluster/v1/stack_input.proto\x12\x36project.planton.provider.civo.civokubernetescluster.v1\x1a@project/planton/provider/civo/civokubernetescluster/v1/api.proto\x1a,project/planton/provider/civo/provider.proto\"\xe4\x01\n\x1f\x43ivoKubernetesClusterStackInput\x12\x65\n\x06target\x18\x01 \x01(\x0b\x32M.project.planton.provider.civo.civokubernetescluster.v1.CivoKubernetesClusterR\x06target\x12Z\n\x0fprovider_config\x18\x02 \x01(\x0b\x32\x31.project.planton.provider.civo.CivoProviderConfigR\x0eproviderConfigB\xcc\x02\n:com.project.planton.provider.civo.civokubernetescluster.v1B\x0fStackInputProtoP\x01\xa2\x02\x05PPPCC\xaa\x02\x36Project.Planton.Provider.Civo.Civokubernetescluster.V1\xca\x02\x36Project\\Planton\\Provider\\Civo\\Civokubernetescluster\\V1\xe2\x02\x42Project\\Planton\\Provider\\Civo\\Civokubernetescluster\\V1\\GPBMetadata\xea\x02;Project::Planton::Provider::Civo::Civokubernetescluster::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.civo.civokubernetescluster.v1.stack_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n:com.project.planton.provider.civo.civokubernetescluster.v1B\017StackInputProtoP\001\242\002\005PPPCC\252\0026Project.Planton.Provider.Civo.Civokubernetescluster.V1\312\0026Project\\Planton\\Provider\\Civo\\Civokubernetescluster\\V1\342\002BProject\\Planton\\Provider\\Civo\\Civokubernetescluster\\V1\\GPBMetadata\352\002;Project::Planton::Provider::Civo::Civokubernetescluster::V1'
  _globals['_CIVOKUBERNETESCLUSTERSTACKINPUT']._serialized_start=245
  _globals['_CIVOKUBERNETESCLUSTERSTACKINPUT']._serialized_end=473
# @@protoc_insertion_point(module_scope)
