# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/civo/civocomputeinstance/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/civo/civocomputeinstance/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHproject/planton/provider/civo/civocomputeinstance/v1/stack_outputs.proto\x12\x34project.planton.provider.civo.civocomputeinstance.v1\"\xcc\x01\n\x1f\x43ivoComputeInstanceStackOutputs\x12\x1f\n\x0binstance_id\x18\x01 \x01(\tR\ninstanceId\x12\x1f\n\x0bpublic_ipv4\x18\x02 \x01(\tR\npublicIpv4\x12!\n\x0cprivate_ipv4\x18\x03 \x01(\tR\x0bprivateIpv4\x12\x16\n\x06status\x18\x04 \x01(\tR\x06status\x12,\n\x12\x63reated_at_rfc3339\x18\x05 \x01(\tR\x10\x63reatedAtRfc3339B\xc4\x02\n8com.project.planton.provider.civo.civocomputeinstance.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPCC\xaa\x02\x34Project.Planton.Provider.Civo.Civocomputeinstance.V1\xca\x02\x34Project\\Planton\\Provider\\Civo\\Civocomputeinstance\\V1\xe2\x02@Project\\Planton\\Provider\\Civo\\Civocomputeinstance\\V1\\GPBMetadata\xea\x02\x39Project::Planton::Provider::Civo::Civocomputeinstance::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.civo.civocomputeinstance.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.project.planton.provider.civo.civocomputeinstance.v1B\021StackOutputsProtoP\001\242\002\005PPPCC\252\0024Project.Planton.Provider.Civo.Civocomputeinstance.V1\312\0024Project\\Planton\\Provider\\Civo\\Civocomputeinstance\\V1\342\002@Project\\Planton\\Provider\\Civo\\Civocomputeinstance\\V1\\GPBMetadata\352\0029Project::Planton::Provider::Civo::Civocomputeinstance::V1'
  _globals['_CIVOCOMPUTEINSTANCESTACKOUTPUTS']._serialized_start=131
  _globals['_CIVOCOMPUTEINSTANCESTACKOUTPUTS']._serialized_end=335
# @@protoc_insertion_point(module_scope)
