# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/connect/gitlabcredential/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/connect/gitlabcredential/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from project.planton.shared.options import options_pb2 as project_dot_planton_dot_shared_dot_options_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9cloud/planton/apis/connect/gitlabcredential/v1/spec.proto\x12.cloud.planton.apis.connect.gitlabcredential.v1\x1a\x1b\x62uf/validate/validate.proto\x1a,project/planton/shared/options/options.proto\"\xff\x01\n\x14GitlabCredentialSpec\x12Q\n\x16gitlab_connection_host\x18\x01 \x01(\tB\x16\x8a\xa6\x1d\x12https://gitlab.comH\x00R\x14gitlabConnectionHost\x88\x01\x01\x12!\n\x08group_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x07groupId\x12)\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x0b\x61\x63\x63\x65ssToken\x12+\n\rrefresh_token\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x0crefreshTokenB\x19\n\x17_gitlab_connection_hostB\x9e\x02\n2com.cloud.planton.apis.connect.gitlabcredential.v1B\tSpecProtoP\x01\xa2\x02\x05\x43PACG\xaa\x02.Cloud.Planton.Apis.Connect.Gitlabcredential.V1\xca\x02.Cloud\\Planton\\Apis\\Connect\\Gitlabcredential\\V1\xe2\x02:Cloud\\Planton\\Apis\\Connect\\Gitlabcredential\\V1\\GPBMetadata\xea\x02\x33\x43loud::Planton::Apis::Connect::Gitlabcredential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.connect.gitlabcredential.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.cloud.planton.apis.connect.gitlabcredential.v1B\tSpecProtoP\001\242\002\005CPACG\252\002.Cloud.Planton.Apis.Connect.Gitlabcredential.V1\312\002.Cloud\\Planton\\Apis\\Connect\\Gitlabcredential\\V1\342\002:Cloud\\Planton\\Apis\\Connect\\Gitlabcredential\\V1\\GPBMetadata\352\0023Cloud::Planton::Apis::Connect::Gitlabcredential::V1'
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['gitlab_connection_host']._loaded_options = None
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['gitlab_connection_host']._serialized_options = b'\212\246\035\022https://gitlab.com'
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['group_id']._loaded_options = None
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['group_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['access_token']._loaded_options = None
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['access_token']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['refresh_token']._loaded_options = None
  _globals['_GITLABCREDENTIALSPEC'].fields_by_name['refresh_token']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITLABCREDENTIALSPEC']._serialized_start=185
  _globals['_GITLABCREDENTIALSPEC']._serialized_end=440
# @@protoc_insertion_point(module_scope)
