# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.connect.dockercredential.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2
from cloud.planton.apis.infrahub.cloudresource.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2


class GcpArtifactRegistryRepoCommandControllerStub(object):
    """gcp-artifact-registry-repo command controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createDockerCredential = channel.unary_unary(
                '/cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController/createDockerCredential',
                request_serializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.FromString,
                _registered_method=True)
        self.createMavenCredential = channel.unary_unary(
                '/cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController/createMavenCredential',
                request_serializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.FromString,
                _registered_method=True)


class GcpArtifactRegistryRepoCommandControllerServicer(object):
    """gcp-artifact-registry-repo command controller
    """

    def createDockerCredential(self, request, context):
        """rpc to create docker-credential from gcp-artifact-registry-repo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createMavenCredential(self, request, context):
        """rpc to create maven-credential from gcp-artifact-registry-repo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GcpArtifactRegistryRepoCommandControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createDockerCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.createDockerCredential,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.SerializeToString,
            ),
            'createMavenCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.createMavenCredential,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GcpArtifactRegistryRepoCommandController(object):
    """gcp-artifact-registry-repo command controller
    """

    @staticmethod
    def createDockerCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController/createDockerCredential',
            cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createMavenCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.infrahub.cloudresource.v1.provider.gcp.gcpartifactregistryrepo.GcpArtifactRegistryRepoCommandController/createMavenCredential',
            cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_io__pb2.CloudResourceId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_connect_dot_dockercredential_dot_v1_dot_api__pb2.DockerCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
