# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/aws/awssecuritygroup/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/aws/awssecuritygroup/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDproject/planton/provider/aws/awssecuritygroup/v1/stack_outputs.proto\x12\x30project.planton.provider.aws.awssecuritygroup.v1\"J\n\x1c\x41wsSecurityGroupStackOutputs\x12*\n\x11security_group_id\x18\x01 \x01(\tR\x0fsecurityGroupIdB\xb0\x02\n4com.project.planton.provider.aws.awssecuritygroup.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPAA\xaa\x02\x30Project.Planton.Provider.Aws.Awssecuritygroup.V1\xca\x02\x30Project\\Planton\\Provider\\Aws\\Awssecuritygroup\\V1\xe2\x02<Project\\Planton\\Provider\\Aws\\Awssecuritygroup\\V1\\GPBMetadata\xea\x02\x35Project::Planton::Provider::Aws::Awssecuritygroup::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.aws.awssecuritygroup.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.project.planton.provider.aws.awssecuritygroup.v1B\021StackOutputsProtoP\001\242\002\005PPPAA\252\0020Project.Planton.Provider.Aws.Awssecuritygroup.V1\312\0020Project\\Planton\\Provider\\Aws\\Awssecuritygroup\\V1\342\002<Project\\Planton\\Provider\\Aws\\Awssecuritygroup\\V1\\GPBMetadata\352\0025Project::Planton::Provider::Aws::Awssecuritygroup::V1'
  _globals['_AWSSECURITYGROUPSTACKOUTPUTS']._serialized_start=122
  _globals['_AWSSECURITYGROUPSTACKOUTPUTS']._serialized_end=196
# @@protoc_insertion_point(module_scope)
