# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/providercredentialmapping/v1/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/providercredentialmapping/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.infrahub.providercredentialmapping.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_providercredentialmapping_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcloud/planton/apis/infrahub/providercredentialmapping/v1/command.proto\x12\x38\x63loud.planton.apis.infrahub.providercredentialmapping.v1\x1a/cloud/planton/apis/commons/apiresource/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1a\x42\x63loud/planton/apis/infrahub/providercredentialmapping/v1/api.proto2\xe7\x05\n*ProviderCredentialMappingCommandController\x12\xb1\x01\n\x05\x61pply\x12S.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x1aS.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x12\xb2\x01\n\x06\x63reate\x12S.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x1aS.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x12\xb2\x01\n\x06update\x12S.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x1aS.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x12\x94\x01\n\x06\x64\x65lete\x12\x35.cloud.planton.apis.commons.apiresource.ApiResourceId\x1aS.cloud.planton.apis.infrahub.providercredentialmapping.v1.ProviderCredentialMapping\x1a\x04\xa0\xff+\x1d\x42\xd3\x02\n<com.cloud.planton.apis.infrahub.providercredentialmapping.v1B\x0c\x43ommandProtoP\x01\xa2\x02\x05\x43PAIP\xaa\x02\x38\x43loud.Planton.Apis.Infrahub.Providercredentialmapping.V1\xca\x02\x38\x43loud\\Planton\\Apis\\Infrahub\\Providercredentialmapping\\V1\xe2\x02\x44\x43loud\\Planton\\Apis\\Infrahub\\Providercredentialmapping\\V1\\GPBMetadata\xea\x02=Cloud::Planton::Apis::Infrahub::Providercredentialmapping::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.providercredentialmapping.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n<com.cloud.planton.apis.infrahub.providercredentialmapping.v1B\014CommandProtoP\001\242\002\005CPAIP\252\0028Cloud.Planton.Apis.Infrahub.Providercredentialmapping.V1\312\0028Cloud\\Planton\\Apis\\Infrahub\\Providercredentialmapping\\V1\342\002DCloud\\Planton\\Apis\\Infrahub\\Providercredentialmapping\\V1\\GPBMetadata\352\002=Cloud::Planton::Apis::Infrahub::Providercredentialmapping::V1'
  _globals['_PROVIDERCREDENTIALMAPPINGCOMMANDCONTROLLER']._loaded_options = None
  _globals['_PROVIDERCREDENTIALMAPPINGCOMMANDCONTROLLER']._serialized_options = b'\240\377+\035'
  _globals['_PROVIDERCREDENTIALMAPPINGCOMMANDCONTROLLER']._serialized_start=316
  _globals['_PROVIDERCREDENTIALMAPPINGCOMMANDCONTROLLER']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
