# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/kubernetes/workload/cronjobkubernetes/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/kubernetes/workload/cronjobkubernetes/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nUproject/planton/provider/kubernetes/workload/cronjobkubernetes/v1/stack_outputs.proto\x12\x41project.planton.provider.kubernetes.workload.cronjobkubernetes.v1\"=\n\x1d\x43ronJobKubernetesStackOutputs\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespaceB\x87\x03\nEcom.project.planton.provider.kubernetes.workload.cronjobkubernetes.v1B\x11StackOutputsProtoP\x01\xa2\x02\x06PPPKWC\xaa\x02\x41Project.Planton.Provider.Kubernetes.Workload.Cronjobkubernetes.V1\xca\x02\x41Project\\Planton\\Provider\\Kubernetes\\Workload\\Cronjobkubernetes\\V1\xe2\x02MProject\\Planton\\Provider\\Kubernetes\\Workload\\Cronjobkubernetes\\V1\\GPBMetadata\xea\x02GProject::Planton::Provider::Kubernetes::Workload::Cronjobkubernetes::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.kubernetes.workload.cronjobkubernetes.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nEcom.project.planton.provider.kubernetes.workload.cronjobkubernetes.v1B\021StackOutputsProtoP\001\242\002\006PPPKWC\252\002AProject.Planton.Provider.Kubernetes.Workload.Cronjobkubernetes.V1\312\002AProject\\Planton\\Provider\\Kubernetes\\Workload\\Cronjobkubernetes\\V1\342\002MProject\\Planton\\Provider\\Kubernetes\\Workload\\Cronjobkubernetes\\V1\\GPBMetadata\352\002GProject::Planton::Provider::Kubernetes::Workload::Cronjobkubernetes::V1'
  _globals['_CRONJOBKUBERNETESSTACKOUTPUTS']._serialized_start=156
  _globals['_CRONJOBKUBERNETESSTACKOUTPUTS']._serialized_end=217
# @@protoc_insertion_point(module_scope)
