# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/integration/gcp/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/integration/gcp/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.integration.gcp import io_pb2 as cloud_dot_planton_dot_apis_dot_integration_dot_gcp_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0cloud/planton/apis/integration/gcp/command.proto\x12\"cloud.planton.apis.integration.gcp\x1a+cloud/planton/apis/integration/gcp/io.proto2\xc0\x01\n\x14GcpCommandController\x12\xa7\x01\n\x15\x61uthorizeCloudAccount\x12\x41.cloud.planton.apis.integration.gcp.AuthorizeGcpCloudAccountInput\x1aK.cloud.planton.apis.integration.gcp.AuthorizeGcpCloudAccountCommandResponseB\xe4\x01\n&com.cloud.planton.apis.integration.gcpB\x0c\x43ommandProtoP\x01\xa2\x02\x05\x43PAIG\xaa\x02\"Cloud.Planton.Apis.Integration.Gcp\xca\x02\"Cloud\\Planton\\Apis\\Integration\\Gcp\xe2\x02.Cloud\\Planton\\Apis\\Integration\\Gcp\\GPBMetadata\xea\x02&Cloud::Planton::Apis::Integration::Gcpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.integration.gcp.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.cloud.planton.apis.integration.gcpB\014CommandProtoP\001\242\002\005CPAIG\252\002\"Cloud.Planton.Apis.Integration.Gcp\312\002\"Cloud\\Planton\\Apis\\Integration\\Gcp\342\002.Cloud\\Planton\\Apis\\Integration\\Gcp\\GPBMetadata\352\002&Cloud::Planton::Apis::Integration::Gcp'
  _globals['_GCPCOMMANDCONTROLLER']._serialized_start=134
  _globals['_GCPCOMMANDCONTROLLER']._serialized_end=326
# @@protoc_insertion_point(module_scope)
