# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/aws/awsiamuser/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/aws/awsiamuser/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5project/planton/provider/aws/awsiamuser/v1/spec.proto\x12*project.planton.provider.aws.awsiamuser.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb6\x03\n\x0e\x41wsIamUserSpec\x12\x41\n\tuser_name\x18\x01 \x01(\tB$\xbaH!r\x1c\x32\x1a^[a-zA-Z0-9+=,.@_-]{1,64}$\xc8\x01\x01R\x08userName\x12L\n\x13managed_policy_arns\x18\x02 \x03(\tB\x1c\xbaH\x19\x92\x01\x16\x18\x01\"\x12r\x10\x32\x0e^arn:aws:iam::R\x11managedPolicyArns\x12\x86\x01\n\x0finline_policies\x18\x03 \x03(\x0b\x32N.project.planton.provider.aws.awsiamuser.v1.AwsIamUserSpec.InlinePoliciesEntryB\r\xbaH\n\x9a\x01\x07\"\x05r\x03\x18\x80\x01R\x0einlinePolicies\x12.\n\x13\x64isable_access_keys\x18\x04 \x01(\x08R\x11\x64isableAccessKeys\x1aZ\n\x13InlinePoliciesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\x05value:\x02\x38\x01\x42\x8a\x02\n.com.project.planton.provider.aws.awsiamuser.v1B\tSpecProtoP\x01\xa2\x02\x05PPPAA\xaa\x02*Project.Planton.Provider.Aws.Awsiamuser.V1\xca\x02*Project\\Planton\\Provider\\Aws\\Awsiamuser\\V1\xe2\x02\x36Project\\Planton\\Provider\\Aws\\Awsiamuser\\V1\\GPBMetadata\xea\x02/Project::Planton::Provider::Aws::Awsiamuser::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.aws.awsiamuser.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.project.planton.provider.aws.awsiamuser.v1B\tSpecProtoP\001\242\002\005PPPAA\252\002*Project.Planton.Provider.Aws.Awsiamuser.V1\312\002*Project\\Planton\\Provider\\Aws\\Awsiamuser\\V1\342\0026Project\\Planton\\Provider\\Aws\\Awsiamuser\\V1\\GPBMetadata\352\002/Project::Planton::Provider::Aws::Awsiamuser::V1'
  _globals['_AWSIAMUSERSPEC_INLINEPOLICIESENTRY']._loaded_options = None
  _globals['_AWSIAMUSERSPEC_INLINEPOLICIESENTRY']._serialized_options = b'8\001'
  _globals['_AWSIAMUSERSPEC'].fields_by_name['user_name']._loaded_options = None
  _globals['_AWSIAMUSERSPEC'].fields_by_name['user_name']._serialized_options = b'\272H!r\0342\032^[a-zA-Z0-9+=,.@_-]{1,64}$\310\001\001'
  _globals['_AWSIAMUSERSPEC'].fields_by_name['managed_policy_arns']._loaded_options = None
  _globals['_AWSIAMUSERSPEC'].fields_by_name['managed_policy_arns']._serialized_options = b'\272H\031\222\001\026\030\001\"\022r\0202\016^arn:aws:iam::'
  _globals['_AWSIAMUSERSPEC'].fields_by_name['inline_policies']._loaded_options = None
  _globals['_AWSIAMUSERSPEC'].fields_by_name['inline_policies']._serialized_options = b'\272H\n\232\001\007\"\005r\003\030\200\001'
  _globals['_AWSIAMUSERSPEC']._serialized_start=161
  _globals['_AWSIAMUSERSPEC']._serialized_end=599
  _globals['_AWSIAMUSERSPEC_INLINEPOLICIESENTRY']._serialized_start=509
  _globals['_AWSIAMUSERSPEC_INLINEPOLICIESENTRY']._serialized_end=599
# @@protoc_insertion_point(module_scope)
