# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/flowcontrolpolicy/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/flowcontrolpolicy/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import selector_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_selector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cloud/planton/apis/infrahub/flowcontrolpolicy/v1/spec.proto\x12\x30\x63loud.planton.apis.infrahub.flowcontrolpolicy.v1\x1a\x35\x63loud/planton/apis/commons/apiresource/selector.proto\"\xda\x01\n\x15\x46lowControlPolicySpec\x12W\n\x08selector\x18\x01 \x01(\x0b\x32;.cloud.planton.apis.commons.apiresource.ApiResourceSelectorR\x08selector\x12h\n\x0c\x66low_control\x18\x02 \x01(\x0b\x32\x45.cloud.planton.apis.infrahub.flowcontrolpolicy.v1.StackJobFlowControlR\x0b\x66lowControl\"\xb8\x02\n\x13StackJobFlowControl\x12\x1b\n\tis_manual\x18\x01 \x01(\x08R\x08isManual\x12=\n\x1b\x64isable_on_lifecycle_events\x18\x02 \x01(\x08R\x18\x64isableOnLifecycleEvents\x12!\n\x0cskip_refresh\x18\x03 \x01(\x08R\x0bskipRefresh\x12\x46\n preview_before_update_or_destroy\x18\x04 \x01(\x08R\x1cpreviewBeforeUpdateOrDestroy\x12Z\n+pause_between_preview_and_update_or_destroy\x18\x05 \x01(\x08R%pauseBetweenPreviewAndUpdateOrDestroyB\xa8\x02\n4com.cloud.planton.apis.infrahub.flowcontrolpolicy.v1B\tSpecProtoP\x01\xa2\x02\x05\x43PAIF\xaa\x02\x30\x43loud.Planton.Apis.Infrahub.Flowcontrolpolicy.V1\xca\x02\x30\x43loud\\Planton\\Apis\\Infrahub\\Flowcontrolpolicy\\V1\xe2\x02<Cloud\\Planton\\Apis\\Infrahub\\Flowcontrolpolicy\\V1\\GPBMetadata\xea\x02\x35\x43loud::Planton::Apis::Infrahub::Flowcontrolpolicy::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.flowcontrolpolicy.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.cloud.planton.apis.infrahub.flowcontrolpolicy.v1B\tSpecProtoP\001\242\002\005CPAIF\252\0020Cloud.Planton.Apis.Infrahub.Flowcontrolpolicy.V1\312\0020Cloud\\Planton\\Apis\\Infrahub\\Flowcontrolpolicy\\V1\342\002<Cloud\\Planton\\Apis\\Infrahub\\Flowcontrolpolicy\\V1\\GPBMetadata\352\0025Cloud::Planton::Apis::Infrahub::Flowcontrolpolicy::V1'
  _globals['_FLOWCONTROLPOLICYSPEC']._serialized_start=169
  _globals['_FLOWCONTROLPOLICYSPEC']._serialized_end=387
  _globals['_STACKJOBFLOWCONTROL']._serialized_start=390
  _globals['_STACKJOBFLOWCONTROL']._serialized_end=702
# @@protoc_insertion_point(module_scope)
