# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.servicehub.githubaction.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2
from cloud.planton.apis.servicehub.githubaction.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_io__pb2


class GithubActionCommandControllerStub(object):
    """github-action command controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.apply = channel.unary_unary(
                '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/apply',
                request_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                _registered_method=True)
        self.create = channel.unary_unary(
                '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/create',
                request_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/update',
                request_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                _registered_method=True)
        self.delete = channel.unary_unary(
                '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/delete',
                request_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_io__pb2.GithubActionId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                _registered_method=True)


class GithubActionCommandControllerServicer(object):
    """github-action command controller
    """

    def apply(self, request, context):
        """create/update a github-action resource
        the authorization and state-operation are determined depending on whether the github-action
        is going to be created or updated which is determined as part of the request execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """create a github-action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """update an existing github-action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """delete a github-action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GithubActionCommandControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'apply': grpc.unary_unary_rpc_method_handler(
                    servicer.apply,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            ),
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_io__pb2.GithubActionId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GithubActionCommandController(object):
    """github-action command controller
    """

    @staticmethod
    def apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/apply',
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/create',
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/update',
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.SerializeToString,
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.servicehub.githubaction.v1.GithubActionCommandController/delete',
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_io__pb2.GithubActionId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2.GithubAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
