# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/servicehub/githubaction/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/servicehub/githubaction/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.servicehub.githubaction.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_servicehub_dot_githubaction_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6cloud/planton/apis/servicehub/githubaction/v1/io.proto\x12-cloud.planton.apis.servicehub.githubaction.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x37\x63loud/planton/apis/servicehub/githubaction/v1/api.proto\".\n\x0eGithubActionId\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"\x8a\x01\n\x10GithubActionList\x12\x1f\n\x0btotal_pages\x18\x01 \x01(\x05R\ntotalPages\x12U\n\x07\x65ntries\x18\x02 \x03(\x0b\x32;.cloud.planton.apis.servicehub.githubaction.v1.GithubActionR\x07\x65ntriesB\x97\x02\n1com.cloud.planton.apis.servicehub.githubaction.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PASG\xaa\x02-Cloud.Planton.Apis.Servicehub.Githubaction.V1\xca\x02-Cloud\\Planton\\Apis\\Servicehub\\Githubaction\\V1\xe2\x02\x39\x43loud\\Planton\\Apis\\Servicehub\\Githubaction\\V1\\GPBMetadata\xea\x02\x32\x43loud::Planton::Apis::Servicehub::Githubaction::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.servicehub.githubaction.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.cloud.planton.apis.servicehub.githubaction.v1B\007IoProtoP\001\242\002\005CPASG\252\002-Cloud.Planton.Apis.Servicehub.Githubaction.V1\312\002-Cloud\\Planton\\Apis\\Servicehub\\Githubaction\\V1\342\0029Cloud\\Planton\\Apis\\Servicehub\\Githubaction\\V1\\GPBMetadata\352\0022Cloud::Planton::Apis::Servicehub::Githubaction::V1'
  _globals['_GITHUBACTIONID'].fields_by_name['value']._loaded_options = None
  _globals['_GITHUBACTIONID'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITHUBACTIONID']._serialized_start=191
  _globals['_GITHUBACTIONID']._serialized_end=237
  _globals['_GITHUBACTIONLIST']._serialized_start=240
  _globals['_GITHUBACTIONLIST']._serialized_end=378
# @@protoc_insertion_point(module_scope)
