# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/cloudresource/v1/provider/aws/awsroute53zone/v1/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/cloudresource/v1/provider/aws/awsroute53zone/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2
from project.planton.provider.aws.awsroute53zone.v1 import api_pb2 as project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYcloud/planton/apis/infrahub/cloudresource/v1/provider/aws/awsroute53zone/v1/command.proto\x12Hcloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1aTcloud/planton/apis/infrahub/cloudresource/v1/provider/aws/awsroute53zone/v1/io.proto\x1a\x38project/planton/provider/aws/awsroute53zone/v1/api.proto2\xfd\x05\n!Route53DnsRecordCommandController\x12\xec\x01\n\x03\x61\x64\x64\x12j.cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.AddOrUpdateRoute53DnsRecordInput\x1a>.project.planton.provider.aws.awsroute53zone.v1.AwsRoute53Zone\"9\xc2\xb8\x18\x35\x08\x05\x10.\"\x0froute53_zone_id*\x1eunauthorized to add dns-record\x12\xf2\x01\n\x06update\x12j.cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.AddOrUpdateRoute53DnsRecordInput\x1a>.project.planton.provider.aws.awsroute53zone.v1.AwsRoute53Zone\"<\xc2\xb8\x18\x38\x08\x05\x10.\"\x0froute53_zone_id*!unauthorized to update dns-record\x12\xed\x01\n\x06\x64\x65lete\x12\x65.cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.DeleteRoute53DnsRecordInput\x1a>.project.planton.provider.aws.awsroute53zone.v1.AwsRoute53Zone\"<\xc2\xb8\x18\x38\x08\x05\x10.\"\x0froute53_zone_id*!unauthorized to delete dns-record\x1a\x04\xa0\xff+.B\xaa\x03\nLcom.cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zoneB\x0c\x43ommandProtoP\x01\xa2\x02\tCPAICVPAA\xaa\x02HCloud.Planton.Apis.Infrahub.Cloudresource.V1.Provider.Aws.Awsroute53zone\xca\x02HCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Aws\\Awsroute53zone\xe2\x02TCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Aws\\Awsroute53zone\\GPBMetadata\xea\x02PCloud::Planton::Apis::Infrahub::Cloudresource::V1::Provider::Aws::Awsroute53zoneb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nLcom.cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zoneB\014CommandProtoP\001\242\002\tCPAICVPAA\252\002HCloud.Planton.Apis.Infrahub.Cloudresource.V1.Provider.Aws.Awsroute53zone\312\002HCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Aws\\Awsroute53zone\342\002TCloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\Provider\\Aws\\Awsroute53zone\\GPBMetadata\352\002PCloud::Planton::Apis::Infrahub::Cloudresource::V1::Provider::Aws::Awsroute53zone'
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER']._loaded_options = None
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER']._serialized_options = b'\240\377+.'
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['add']._loaded_options = None
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['add']._serialized_options = b'\302\270\0305\010\005\020.\"\017route53_zone_id*\036unauthorized to add dns-record'
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['update']._loaded_options = None
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['update']._serialized_options = b'\302\270\0308\010\005\020.\"\017route53_zone_id*!unauthorized to update dns-record'
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['delete']._loaded_options = None
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER'].methods_by_name['delete']._serialized_options = b'\302\270\0308\010\005\020.\"\017route53_zone_id*!unauthorized to delete dns-record'
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER']._serialized_start=453
  _globals['_ROUTE53DNSRECORDCOMMANDCONTROLLER']._serialized_end=1218
# @@protoc_insertion_point(module_scope)
