# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2
from project.planton.provider.aws.awsroute53zone.v1 import api_pb2 as project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2


class Route53DnsRecordCommandControllerStub(object):
    """route53-zone dns-record command controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/add',
                request_serializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.SerializeToString,
                response_deserializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/update',
                request_serializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.SerializeToString,
                response_deserializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
                _registered_method=True)
        self.delete = channel.unary_unary(
                '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/delete',
                request_serializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.DeleteRoute53DnsRecordInput.SerializeToString,
                response_deserializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
                _registered_method=True)


class Route53DnsRecordCommandControllerServicer(object):
    """route53-zone dns-record command controller
    """

    def add(self, request, context):
        """add a new dns-record to route53-zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """update an existing dns-record in route53-zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """delete a dns-record from a route53-zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Route53DnsRecordCommandControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.FromString,
                    response_serializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.FromString,
                    response_serializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.DeleteRoute53DnsRecordInput.FromString,
                    response_serializer=project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Route53DnsRecordCommandController(object):
    """route53-zone dns-record command controller
    """

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/add',
            cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.SerializeToString,
            project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/update',
            cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.AddOrUpdateRoute53DnsRecordInput.SerializeToString,
            project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.infrahub.cloudresource.v1.provider.aws.awsroute53zone.Route53DnsRecordCommandController/delete',
            cloud_dot_planton_dot_apis_dot_infrahub_dot_cloudresource_dot_v1_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_io__pb2.DeleteRoute53DnsRecordInput.SerializeToString,
            project_dot_planton_dot_provider_dot_aws_dot_awsroute53zone_dot_v1_dot_api__pb2.AwsRoute53Zone.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
