# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/cloudresource/v1/graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/cloudresource/v1/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from project.planton.shared.cloudresourcekind import cloud_resource_kind_pb2 as project_dot_planton_dot_shared_dot_cloudresourcekind_dot_cloud__resource__kind__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8cloud/planton/apis/infrahub/cloudresource/v1/graph.proto\x12,cloud.planton.apis.infrahub.cloudresource.v1\x1a\x42project/planton/shared/cloudresourcekind/cloud_resource_kind.proto\"\x93\x02\n\x16\x43loudResourceGraphView\x12\x10\n\x03org\x18\x01 \x01(\tR\x03org\x12\x10\n\x03\x65nv\x18\x02 \x01(\tR\x03\x65nv\x12Z\n\x05nodes\x18\x03 \x03(\x0b\x32\x44.cloud.planton.apis.infrahub.cloudresource.v1.CloudResourceGraphNodeR\x05nodes\x12Z\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x44.cloud.planton.apis.infrahub.cloudresource.v1.CloudResourceGraphEdgeR\x05\x65\x64ges\x12\x1d\n\ntopo_order\x18\x05 \x03(\tR\ttopoOrder\"\xb1\x01\n\x16\x43loudResourceGraphNode\x12\x10\n\x03org\x18\x01 \x01(\tR\x03org\x12\x10\n\x03\x65nv\x18\x02 \x01(\tR\x03\x65nv\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n\x02id\x18\x04 \x01(\tR\x02id\x12O\n\x04kind\x18\x05 \x01(\x0e\x32;.project.planton.shared.cloudresourcekind.CloudResourceKindR\x04kind\"\xaa\x01\n\x16\x43loudResourceGraphEdge\x12\x1b\n\tsource_id\x18\x01 \x01(\tR\x08sourceId\x12\x1b\n\ttarget_id\x18\x02 \x01(\tR\x08targetId\x12*\n\x11source_field_path\x18\x03 \x01(\tR\x0fsourceFieldPath\x12*\n\x11target_field_path\x18\x04 \x01(\tR\x0ftargetFieldPath\"\xd3\x01\n\x1b\x43loudResourceGraphReference\x12*\n\x11source_field_path\x18\x01 \x01(\tR\x0fsourceFieldPath\x12*\n\x11target_field_path\x18\x02 \x01(\tR\x0ftargetFieldPath\x12\\\n\x06target\x18\x03 \x01(\x0b\x32\x44.cloud.planton.apis.infrahub.cloudresource.v1.CloudResourceGraphNodeR\x06targetB\x95\x02\n0com.cloud.planton.apis.infrahub.cloudresource.v1B\nGraphProtoP\x01\xa2\x02\x05\x43PAIC\xaa\x02,Cloud.Planton.Apis.Infrahub.Cloudresource.V1\xca\x02,Cloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\xe2\x02\x38\x43loud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\GPBMetadata\xea\x02\x31\x43loud::Planton::Apis::Infrahub::Cloudresource::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.cloudresource.v1.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.cloud.planton.apis.infrahub.cloudresource.v1B\nGraphProtoP\001\242\002\005CPAIC\252\002,Cloud.Planton.Apis.Infrahub.Cloudresource.V1\312\002,Cloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\342\0028Cloud\\Planton\\Apis\\Infrahub\\Cloudresource\\V1\\GPBMetadata\352\0021Cloud::Planton::Apis::Infrahub::Cloudresource::V1'
  _globals['_CLOUDRESOURCEGRAPHVIEW']._serialized_start=175
  _globals['_CLOUDRESOURCEGRAPHVIEW']._serialized_end=450
  _globals['_CLOUDRESOURCEGRAPHNODE']._serialized_start=453
  _globals['_CLOUDRESOURCEGRAPHNODE']._serialized_end=630
  _globals['_CLOUDRESOURCEGRAPHEDGE']._serialized_start=633
  _globals['_CLOUDRESOURCEGRAPHEDGE']._serialized_end=803
  _globals['_CLOUDRESOURCEGRAPHREFERENCE']._serialized_start=806
  _globals['_CLOUDRESOURCEGRAPHREFERENCE']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
