# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/gcp/provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/gcp/provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+project/planton/provider/gcp/provider.proto\x12\x1cproject.planton.provider.gcp\x1a\x1b\x62uf/validate/validate.proto\"X\n\x11GcpProviderConfig\x12\x43\n\x1aservice_account_key_base64\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x17serviceAccountKeyBase64B\xc5\x01\n com.project.planton.provider.gcpB\rProviderProtoP\x01\xa2\x02\x04PPPG\xaa\x02\x1cProject.Planton.Provider.Gcp\xca\x02\x1cProject\\Planton\\Provider\\Gcp\xe2\x02(Project\\Planton\\Provider\\Gcp\\GPBMetadata\xea\x02\x1fProject::Planton::Provider::Gcpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.gcp.provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.project.planton.provider.gcpB\rProviderProtoP\001\242\002\004PPPG\252\002\034Project.Planton.Provider.Gcp\312\002\034Project\\Planton\\Provider\\Gcp\342\002(Project\\Planton\\Provider\\Gcp\\GPBMetadata\352\002\037Project::Planton::Provider::Gcp'
  _globals['_GCPPROVIDERCONFIG'].fields_by_name['service_account_key_base64']._loaded_options = None
  _globals['_GCPPROVIDERCONFIG'].fields_by_name['service_account_key_base64']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GCPPROVIDERCONFIG']._serialized_start=106
  _globals['_GCPPROVIDERCONFIG']._serialized_end=194
# @@protoc_insertion_point(module_scope)
