# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/cloudflare/cloudflarednszone/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/cloudflare/cloudflarednszone/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLproject/planton/provider/cloudflare/cloudflarednszone/v1/stack_outputs.proto\x12\x38project.planton.provider.cloudflare.cloudflarednszone.v1\"Z\n\x1d\x43loudflareDnsZoneStackOutputs\x12\x17\n\x07zone_id\x18\x01 \x01(\tR\x06zoneId\x12 \n\x0bnameservers\x18\x02 \x03(\tR\x0bnameserversB\xd8\x02\n<com.project.planton.provider.cloudflare.cloudflarednszone.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPCC\xaa\x02\x38Project.Planton.Provider.Cloudflare.Cloudflarednszone.V1\xca\x02\x38Project\\Planton\\Provider\\Cloudflare\\Cloudflarednszone\\V1\xe2\x02\x44Project\\Planton\\Provider\\Cloudflare\\Cloudflarednszone\\V1\\GPBMetadata\xea\x02=Project::Planton::Provider::Cloudflare::Cloudflarednszone::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.cloudflare.cloudflarednszone.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n<com.project.planton.provider.cloudflare.cloudflarednszone.v1B\021StackOutputsProtoP\001\242\002\005PPPCC\252\0028Project.Planton.Provider.Cloudflare.Cloudflarednszone.V1\312\0028Project\\Planton\\Provider\\Cloudflare\\Cloudflarednszone\\V1\342\002DProject\\Planton\\Provider\\Cloudflare\\Cloudflarednszone\\V1\\GPBMetadata\352\002=Project::Planton::Provider::Cloudflare::Cloudflarednszone::V1'
  _globals['_CLOUDFLAREDNSZONESTACKOUTPUTS']._serialized_start=138
  _globals['_CLOUDFLAREDNSZONESTACKOUTPUTS']._serialized_end=228
# @@protoc_insertion_point(module_scope)
