# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/connect/gitcredential/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/connect/gitcredential/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6cloud/planton/apis/connect/gitcredential/v1/spec.proto\x12+cloud.planton.apis.connect.gitcredential.v1\"\xa7\x01\n\x11GitCredentialSpec\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\x12&\n\x0fssh_private_key\x18\x03 \x01(\tR\rsshPrivateKey\x12\x32\n\x15personal_access_token\x18\x04 \x01(\tR\x13personalAccessTokenB\x8f\x02\n/com.cloud.planton.apis.connect.gitcredential.v1B\tSpecProtoP\x01\xa2\x02\x05\x43PACG\xaa\x02+Cloud.Planton.Apis.Connect.Gitcredential.V1\xca\x02+Cloud\\Planton\\Apis\\Connect\\Gitcredential\\V1\xe2\x02\x37\x43loud\\Planton\\Apis\\Connect\\Gitcredential\\V1\\GPBMetadata\xea\x02\x30\x43loud::Planton::Apis::Connect::Gitcredential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.connect.gitcredential.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.cloud.planton.apis.connect.gitcredential.v1B\tSpecProtoP\001\242\002\005CPACG\252\002+Cloud.Planton.Apis.Connect.Gitcredential.V1\312\002+Cloud\\Planton\\Apis\\Connect\\Gitcredential\\V1\342\0027Cloud\\Planton\\Apis\\Connect\\Gitcredential\\V1\\GPBMetadata\352\0020Cloud::Planton::Apis::Connect::Gitcredential::V1'
  _globals['_GITCREDENTIALSPEC']._serialized_start=104
  _globals['_GITCREDENTIALSPEC']._serialized_end=271
# @@protoc_insertion_point(module_scope)
