# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import io_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_io__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x12\x34\x63loud.planton.apis.iam.iampolicy.v1.rpcauthorization\x1a=cloud/planton/apis/iam/iampolicy/v1/rpcauthorization/io.proto\x1a google/protobuf/descriptor.proto:\x86\x01\n\x06\x63onfig\x12\x1e.google.protobuf.MethodOptions\x18\x88\x87\x03 \x01(\x0b\x32L.cloud.planton.apis.iam.iampolicy.v1.rpcauthorization.RpcAuthorizationConfigR\x06\x63onfig:=\n\tis_public\x12\x1e.google.protobuf.MethodOptions\x18\x89\x87\x03 \x01(\x08R\x08isPublic:T\n\x15is_skip_authorization\x12\x1e.google.protobuf.MethodOptions\x18\x8a\x87\x03 \x01(\x08R\x13isSkipAuthorizationB\xc8\x02\n8com.cloud.planton.apis.iam.iampolicy.v1.rpcauthorizationB\x12MethodOptionsProtoP\x01\xa2\x02\x07\x43PAIIVR\xaa\x02\x34\x43loud.Planton.Apis.Iam.Iampolicy.V1.Rpcauthorization\xca\x02\x34\x43loud\\Planton\\Apis\\Iam\\Iampolicy\\V1\\Rpcauthorization\xe2\x02@Cloud\\Planton\\Apis\\Iam\\Iampolicy\\V1\\Rpcauthorization\\GPBMetadata\xea\x02:Cloud::Planton::Apis::Iam::Iampolicy::V1::Rpcauthorizationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.iam.iampolicy.v1.rpcauthorization.method_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.cloud.planton.apis.iam.iampolicy.v1.rpcauthorizationB\022MethodOptionsProtoP\001\242\002\007CPAIIVR\252\0024Cloud.Planton.Apis.Iam.Iampolicy.V1.Rpcauthorization\312\0024Cloud\\Planton\\Apis\\Iam\\Iampolicy\\V1\\Rpcauthorization\342\002@Cloud\\Planton\\Apis\\Iam\\Iampolicy\\V1\\Rpcauthorization\\GPBMetadata\352\002:Cloud::Planton::Apis::Iam::Iampolicy::V1::Rpcauthorization'
# @@protoc_insertion_point(module_scope)
