# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/connect/snowflakecredential/v1/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/connect/snowflakecredential/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.connect.snowflakecredential.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_snowflakecredential_dot_v1_dot_api__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cloud/planton/apis/connect/snowflakecredential/v1/command.proto\x12\x31\x63loud.planton.apis.connect.snowflakecredential.v1\x1a/cloud/planton/apis/commons/apiresource/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1a;cloud/planton/apis/connect/snowflakecredential/v1/api.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto2\xcd\x06\n$SnowflakeCredentialCommandController\x12\x97\x01\n\x05\x61pply\x12\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\x1a\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\x12\xdd\x01\n\x06\x63reate\x12\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\x1a\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\"C\xc2\xb8\x18?\x08\x13\x10\r\"\x0cmetadata.org*+unauthorized to create snowflake-credential\x12\xdc\x01\n\x06update\x12\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\x1a\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\"B\xc2\xb8\x18>\x08\x05\x10j\"\x0bmetadata.id*+unauthorized to update snowflake-credential\x12\xc5\x01\n\x06\x64\x65lete\x12\x35.cloud.planton.apis.commons.apiresource.ApiResourceId\x1a\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\"<\xc2\xb8\x18\x38\x08\x02\x10j\"\x05value*+unauthorized to delete snowflake-credential\x1a\x04\xa0\xff+jB\xb0\x02\n5com.cloud.planton.apis.connect.snowflakecredential.v1B\x0c\x43ommandProtoP\x01\xa2\x02\x05\x43PACS\xaa\x02\x31\x43loud.Planton.Apis.Connect.Snowflakecredential.V1\xca\x02\x31\x43loud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\xe2\x02=Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\\GPBMetadata\xea\x02\x36\x43loud::Planton::Apis::Connect::Snowflakecredential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.connect.snowflakecredential.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.cloud.planton.apis.connect.snowflakecredential.v1B\014CommandProtoP\001\242\002\005CPACS\252\0021Cloud.Planton.Apis.Connect.Snowflakecredential.V1\312\0021Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\342\002=Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\\GPBMetadata\352\0026Cloud::Planton::Apis::Connect::Snowflakecredential::V1'
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER']._serialized_options = b'\240\377+j'
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['create']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['create']._serialized_options = b'\302\270\030?\010\023\020\r\"\014metadata.org*+unauthorized to create snowflake-credential'
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['update']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['update']._serialized_options = b'\302\270\030>\010\005\020j\"\013metadata.id*+unauthorized to update snowflake-credential'
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['delete']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER'].methods_by_name['delete']._serialized_options = b'\302\270\0308\010\002\020j\"\005value*+unauthorized to delete snowflake-credential'
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER']._serialized_start=370
  _globals['_SNOWFLAKECREDENTIALCOMMANDCONTROLLER']._serialized_end=1215
# @@protoc_insertion_point(module_scope)
