# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/connect/snowflakecredential/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/connect/snowflakecredential/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import find_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2
from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.connect.snowflakecredential.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_snowflakecredential_dot_v1_dot_api__pb2
from cloud.planton.apis.connect.snowflakecredential.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_snowflakecredential_dot_v1_dot_io__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=cloud/planton/apis/connect/snowflakecredential/v1/query.proto\x12\x31\x63loud.planton.apis.connect.snowflakecredential.v1\x1a\x31\x63loud/planton/apis/commons/apiresource/find.proto\x1a/cloud/planton/apis/commons/apiresource/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1a;cloud/planton/apis/connect/snowflakecredential/v1/api.proto\x1a:cloud/planton/apis/connect/snowflakecredential/v1/io.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto2\xbb\x03\n\"SnowflakeCredentialQueryController\x12\xc2\x01\n\x03get\x12\x35.cloud.planton.apis.commons.apiresource.ApiResourceId\x1a\x46.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredential\"<\xc2\xb8\x18\x38\x08\x03\x10j\"\x05value*+unauthorized to lookup snowflake-credential\x12\xc9\x01\n\x04\x66ind\x12?.cloud.planton.apis.commons.apiresource.FindApiResourcesRequest\x1aJ.cloud.planton.apis.connect.snowflakecredential.v1.SnowflakeCredentialList\"4\xc2\xb8\x18\x30\x08\x08\x10\x0b**unauthorized to find snowflake-credentials\x1a\x04\xa0\xff+jB\xae\x02\n5com.cloud.planton.apis.connect.snowflakecredential.v1B\nQueryProtoP\x01\xa2\x02\x05\x43PACS\xaa\x02\x31\x43loud.Planton.Apis.Connect.Snowflakecredential.V1\xca\x02\x31\x43loud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\xe2\x02=Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\\GPBMetadata\xea\x02\x36\x43loud::Planton::Apis::Connect::Snowflakecredential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.connect.snowflakecredential.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.cloud.planton.apis.connect.snowflakecredential.v1B\nQueryProtoP\001\242\002\005CPACS\252\0021Cloud.Planton.Apis.Connect.Snowflakecredential.V1\312\0021Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\342\002=Cloud\\Planton\\Apis\\Connect\\Snowflakecredential\\V1\\GPBMetadata\352\0026Cloud::Planton::Apis::Connect::Snowflakecredential::V1'
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER']._serialized_options = b'\240\377+j'
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER'].methods_by_name['get']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER'].methods_by_name['get']._serialized_options = b'\302\270\0308\010\003\020j\"\005value*+unauthorized to lookup snowflake-credential'
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER'].methods_by_name['find']._loaded_options = None
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER'].methods_by_name['find']._serialized_options = b'\302\270\0300\010\010\020\013**unauthorized to find snowflake-credentials'
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER']._serialized_start=479
  _globals['_SNOWFLAKECREDENTIALQUERYCONTROLLER']._serialized_end=922
# @@protoc_insertion_point(module_scope)
