# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/kubernetes/workload/neo4jkubernetes/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/kubernetes/workload/neo4jkubernetes/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSproject/planton/provider/kubernetes/workload/neo4jkubernetes/v1/stack_outputs.proto\x12?project.planton.provider.kubernetes.workload.neo4jkubernetes.v1\"\xbf\x01\n\x1bNeo4jKubernetesStackOutputs\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\x12\x33\n\x16\x62olt_uri_kube_endpoint\x18\x03 \x01(\tR\x13\x62oltUriKubeEndpoint\x12\x33\n\x16http_uri_kube_endpoint\x18\x04 \x01(\tR\x13httpUriKubeEndpointB\xfd\x02\nCcom.project.planton.provider.kubernetes.workload.neo4jkubernetes.v1B\x11StackOutputsProtoP\x01\xa2\x02\x06PPPKWN\xaa\x02?Project.Planton.Provider.Kubernetes.Workload.Neo4jkubernetes.V1\xca\x02?Project\\Planton\\Provider\\Kubernetes\\Workload\\Neo4jkubernetes\\V1\xe2\x02KProject\\Planton\\Provider\\Kubernetes\\Workload\\Neo4jkubernetes\\V1\\GPBMetadata\xea\x02\x45Project::Planton::Provider::Kubernetes::Workload::Neo4jkubernetes::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.kubernetes.workload.neo4jkubernetes.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nCcom.project.planton.provider.kubernetes.workload.neo4jkubernetes.v1B\021StackOutputsProtoP\001\242\002\006PPPKWN\252\002?Project.Planton.Provider.Kubernetes.Workload.Neo4jkubernetes.V1\312\002?Project\\Planton\\Provider\\Kubernetes\\Workload\\Neo4jkubernetes\\V1\342\002KProject\\Planton\\Provider\\Kubernetes\\Workload\\Neo4jkubernetes\\V1\\GPBMetadata\352\002EProject::Planton::Provider::Kubernetes::Workload::Neo4jkubernetes::V1'
  _globals['_NEO4JKUBERNETESSTACKOUTPUTS']._serialized_start=153
  _globals['_NEO4JKUBERNETESSTACKOUTPUTS']._serialized_end=344
# @@protoc_insertion_point(module_scope)
