# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/iam/iamrole/v1/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/iam/iamrole/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.iam.iamrole.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iamrole_dot_v1_dot_api__pb2
from cloud.planton.apis.iam.iamrole.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iamrole_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cloud/planton/apis/iam/iamrole/v1/command.proto\x12!cloud.planton.apis.iam.iamrole.v1\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1a+cloud/planton/apis/iam/iamrole/v1/api.proto\x1a*cloud/planton/apis/iam/iamrole/v1/io.proto2\xc6\x03\n\x18IamRoleCommandController\x12\x8b\x01\n\x06\x63reate\x12*.cloud.planton.apis.iam.iamrole.v1.IamRole\x1a*.cloud.planton.apis.iam.iamrole.v1.IamRole\")\xc2\xb8\x18%\x08\t\x10\x0b*\x1funauthorized to create iam role\x12\x8b\x01\n\x06update\x12*.cloud.planton.apis.iam.iamrole.v1.IamRole\x1a*.cloud.planton.apis.iam.iamrole.v1.IamRole\")\xc2\xb8\x18%\x08\t\x10\x0b*\x1funauthorized to update iam role\x12\x8d\x01\n\x06\x64\x65lete\x12,.cloud.planton.apis.iam.iamrole.v1.IamRoleId\x1a*.cloud.planton.apis.iam.iamrole.v1.IamRole\")\xc2\xb8\x18%\x08\t\x10\x0b*\x1funauthorized to delete iam roleB\xe0\x01\n%com.cloud.planton.apis.iam.iamrole.v1B\x0c\x43ommandProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02!Cloud.Planton.Apis.Iam.Iamrole.V1\xca\x02!Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\xe2\x02-Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\\GPBMetadata\xea\x02&Cloud::Planton::Apis::Iam::Iamrole::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.iam.iamrole.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.cloud.planton.apis.iam.iamrole.v1B\014CommandProtoP\001\242\002\005CPAII\252\002!Cloud.Planton.Apis.Iam.Iamrole.V1\312\002!Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\342\002-Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\\GPBMetadata\352\002&Cloud::Planton::Apis::Iam::Iamrole::V1'
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['create']._loaded_options = None
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['create']._serialized_options = b'\302\270\030%\010\t\020\013*\037unauthorized to create iam role'
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['update']._loaded_options = None
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['update']._serialized_options = b'\302\270\030%\010\t\020\013*\037unauthorized to update iam role'
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['delete']._loaded_options = None
  _globals['_IAMROLECOMMANDCONTROLLER'].methods_by_name['delete']._serialized_options = b'\302\270\030%\010\t\020\013*\037unauthorized to delete iam role'
  _globals['_IAMROLECOMMANDCONTROLLER']._serialized_start=251
  _globals['_IAMROLECOMMANDCONTROLLER']._serialized_end=705
# @@protoc_insertion_point(module_scope)
