# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/iam/iamrole/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/iam/iamrole/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.rpc import pagination_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_rpc_dot_pagination__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.iam.iamrole.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iamrole_dot_v1_dot_api__pb2
from cloud.planton.apis.iam.iamrole.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iamrole_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-cloud/planton/apis/iam/iamrole/v1/query.proto\x12!cloud.planton.apis.iam.iamrole.v1\x1a/cloud/planton/apis/commons/rpc/pagination.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1a+cloud/planton/apis/iam/iamrole/v1/api.proto\x1a*cloud/planton/apis/iam/iamrole/v1/io.proto2\xd0\x04\n\x16IamRoleQueryController\x12\x89\x01\n\x04list\x12(.cloud.planton.apis.commons.rpc.PageInfo\x1a..cloud.planton.apis.iam.iamrole.v1.IamRoleList\"\'\xc2\xb8\x18#\x08\t\x10\x0b*\x1dunauthorized to list iam role\x12\x65\n\x03get\x12,.cloud.planton.apis.iam.iamrole.v1.IamRoleId\x1a*.cloud.planton.apis.iam.iamrole.v1.IamRole\"\x04\xd0\xb8\x18\x01\x12\xa3\x01\n%findByApiResourceKindAndPrincipalType\x12G.cloud.planton.apis.iam.iamrole.v1.ApiResourceKindAndPrincipalTypeInput\x1a+.cloud.planton.apis.iam.iamrole.v1.IamRoles\"\x04\xd0\xb8\x18\x01\x12\x9c\x01\n%getIamPrincipalTypesByApiResourceKind\x12:.cloud.planton.apis.iam.iamrole.v1.IamApiResourceKindInput\x1a\x31.cloud.planton.apis.iam.iamrole.v1.PrincipalTypes\"\x04\xd0\xb8\x18\x01\x42\xde\x01\n%com.cloud.planton.apis.iam.iamrole.v1B\nQueryProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02!Cloud.Planton.Apis.Iam.Iamrole.V1\xca\x02!Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\xe2\x02-Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\\GPBMetadata\xea\x02&Cloud::Planton::Apis::Iam::Iamrole::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.iam.iamrole.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.cloud.planton.apis.iam.iamrole.v1B\nQueryProtoP\001\242\002\005CPAII\252\002!Cloud.Planton.Apis.Iam.Iamrole.V1\312\002!Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\342\002-Cloud\\Planton\\Apis\\Iam\\Iamrole\\V1\\GPBMetadata\352\002&Cloud::Planton::Apis::Iam::Iamrole::V1'
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['list']._loaded_options = None
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['list']._serialized_options = b'\302\270\030#\010\t\020\013*\035unauthorized to list iam role'
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['get']._loaded_options = None
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['get']._serialized_options = b'\320\270\030\001'
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['findByApiResourceKindAndPrincipalType']._loaded_options = None
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['findByApiResourceKindAndPrincipalType']._serialized_options = b'\320\270\030\001'
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['getIamPrincipalTypesByApiResourceKind']._loaded_options = None
  _globals['_IAMROLEQUERYCONTROLLER'].methods_by_name['getIamPrincipalTypesByApiResourceKind']._serialized_options = b'\320\270\030\001'
  _globals['_IAMROLEQUERYCONTROLLER']._serialized_start=298
  _globals['_IAMROLEQUERYCONTROLLER']._serialized_end=890
# @@protoc_insertion_point(module_scope)
