# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.commons.apiresource import find_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2
from cloud.planton.apis.resourcemanager.organization.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_resourcemanager_dot_organization_dot_v1_dot_io__pb2
from cloud.planton.apis.secretsmanager.secret.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2
from cloud.planton.apis.secretsmanager.secret.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2


class SecretQueryControllerStub(object):
    """secret query controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/get',
                request_serializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.FromString,
                _registered_method=True)
        self.find = channel.unary_unary(
                '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/find',
                request_serializer=cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2.FindApiResourcesRequest.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretList.FromString,
                _registered_method=True)
        self.getByOrgBySlug = channel.unary_unary(
                '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/getByOrgBySlug',
                request_serializer=cloud_dot_planton_dot_apis_dot_resourcemanager_dot_organization_dot_v1_dot_io__pb2.ByOrgBySlugRequest.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.FromString,
                _registered_method=True)


class SecretQueryControllerServicer(object):
    """secret query controller
    """

    def get(self, request, context):
        """look up secret using secret id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def find(self, request, context):
        """find secrets with pagination and filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getByOrgBySlug(self, request, context):
        """look up secret using organization id and secret slug
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretQueryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.SerializeToString,
            ),
            'find': grpc.unary_unary_rpc_method_handler(
                    servicer.find,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2.FindApiResourcesRequest.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretList.SerializeToString,
            ),
            'getByOrgBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.getByOrgBySlug,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_resourcemanager_dot_organization_dot_v1_dot_io__pb2.ByOrgBySlugRequest.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretQueryController(object):
    """secret query controller
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/get',
            cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/find',
            cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2.FindApiResourcesRequest.SerializeToString,
            cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_io__pb2.SecretList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getByOrgBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.secretsmanager.secret.v1.SecretQueryController/getByOrgBySlug',
            cloud_dot_planton_dot_apis_dot_resourcemanager_dot_organization_dot_v1_dot_io__pb2.ByOrgBySlugRequest.SerializeToString,
            cloud_dot_planton_dot_apis_dot_secretsmanager_dot_secret_dot_v1_dot_api__pb2.Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
