# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/search/quickaction/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/search/quickaction/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource.apiresourcekind import api_resource_kind_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_apiresourcekind_dot_api__resource__kind__pb2
from cloud.planton.apis.commons.apiresource import field_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_field__options__pb2
from project.planton.shared.cloudresourcekind import cloud_resource_kind_pb2 as project_dot_planton_dot_shared_dot_cloudresourcekind_dot_cloud__resource__kind__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3cloud/planton/apis/search/quickaction/v1/spec.proto\x12(cloud.planton.apis.search.quickaction.v1\x1aNcloud/planton/apis/commons/apiresource/apiresourcekind/api_resource_kind.proto\x1a:cloud/planton/apis/commons/apiresource/field_options.proto\x1a\x42project/planton/shared/cloudresourcekind/cloud_resource_kind.proto\"\x8b\x04\n\x0fQuickActionSpec\x12\x9b\x01\n\x11\x61pi_resource_kind\x18\x01 \x01(\x0e\x32G.cloud.planton.apis.commons.apiresource.apiresourcekind.ApiResourceKindB&\xb8\xb8\x18\x01\xc2\xb8\x18\x1equick_action_api_resource_kindR\x0f\x61piResourceKind\x12\x88\x01\n\x13\x63loud_resource_kind\x18\x02 \x01(\x0e\x32;.project.planton.shared.cloudresourcekind.CloudResourceKindB\x1b\xb8\xb8\x18\x01\xc2\xb8\x18\x13\x63loud_resource_kindR\x11\x63loudResourceKind\x12u\n\x0b\x61\x63tion_type\x18\x03 \x01(\x0e\x32\x39.cloud.planton.apis.search.quickaction.v1.QuickActionTypeB\x19\xb8\xb8\x18\x01\xc2\xb8\x18\x11quick_action_typeR\nactionType\x12+\n\x08icon_url\x18\x04 \x01(\tB\x10\xb8\xb8\x18\x01\xc2\xb8\x18\x08icon_urlR\x07iconUrl\x12+\n\x08is_ready\x18\x05 \x01(\x08\x42\x10\xb8\xb8\x18\x01\xc2\xb8\x18\x08is_readyR\x07isReady*J\n\x0fQuickActionType\x12!\n\x1dquick_action_type_unspecified\x10\x00\x12\n\n\x06\x63reate\x10\x01\x12\x08\n\x04list\x10\x02\x42\x80\x02\n,com.cloud.planton.apis.search.quickaction.v1B\tSpecProtoP\x01\xa2\x02\x05\x43PASQ\xaa\x02(Cloud.Planton.Apis.Search.Quickaction.V1\xca\x02(Cloud\\Planton\\Apis\\Search\\Quickaction\\V1\xe2\x02\x34\x43loud\\Planton\\Apis\\Search\\Quickaction\\V1\\GPBMetadata\xea\x02-Cloud::Planton::Apis::Search::Quickaction::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.search.quickaction.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.cloud.planton.apis.search.quickaction.v1B\tSpecProtoP\001\242\002\005CPASQ\252\002(Cloud.Planton.Apis.Search.Quickaction.V1\312\002(Cloud\\Planton\\Apis\\Search\\Quickaction\\V1\342\0024Cloud\\Planton\\Apis\\Search\\Quickaction\\V1\\GPBMetadata\352\002-Cloud::Planton::Apis::Search::Quickaction::V1'
  _globals['_QUICKACTIONSPEC'].fields_by_name['api_resource_kind']._loaded_options = None
  _globals['_QUICKACTIONSPEC'].fields_by_name['api_resource_kind']._serialized_options = b'\270\270\030\001\302\270\030\036quick_action_api_resource_kind'
  _globals['_QUICKACTIONSPEC'].fields_by_name['cloud_resource_kind']._loaded_options = None
  _globals['_QUICKACTIONSPEC'].fields_by_name['cloud_resource_kind']._serialized_options = b'\270\270\030\001\302\270\030\023cloud_resource_kind'
  _globals['_QUICKACTIONSPEC'].fields_by_name['action_type']._loaded_options = None
  _globals['_QUICKACTIONSPEC'].fields_by_name['action_type']._serialized_options = b'\270\270\030\001\302\270\030\021quick_action_type'
  _globals['_QUICKACTIONSPEC'].fields_by_name['icon_url']._loaded_options = None
  _globals['_QUICKACTIONSPEC'].fields_by_name['icon_url']._serialized_options = b'\270\270\030\001\302\270\030\010icon_url'
  _globals['_QUICKACTIONSPEC'].fields_by_name['is_ready']._loaded_options = None
  _globals['_QUICKACTIONSPEC'].fields_by_name['is_ready']._serialized_options = b'\270\270\030\001\302\270\030\010is_ready'
  _globals['_QUICKACTIONTYPE']._serialized_start=831
  _globals['_QUICKACTIONTYPE']._serialized_end=905
  _globals['_QUICKACTIONSPEC']._serialized_start=306
  _globals['_QUICKACTIONSPEC']._serialized_end=829
# @@protoc_insertion_point(module_scope)
