# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/copilot/copilotchat/chatmessage/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/copilot/copilotchat/chatmessage/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.copilot.copilotchat.chatmessage.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_copilot_dot_copilotchat_dot_chatmessage_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>cloud/planton/apis/copilot/copilotchat/chatmessage/v1/io.proto\x12\x35\x63loud.planton.apis.copilot.copilotchat.chatmessage.v1\x1a\x1b\x62uf/validate/validate.proto\x1a?cloud/planton/apis/copilot/copilotchat/chatmessage/v1/api.proto\"-\n\rChatMessageId\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"E\n\x10SendMessageInput\x12\x17\n\x07\x63hat_id\x18\x01 \x01(\tR\x06\x63hatId\x12\x18\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent\"l\n\x0c\x43hatMessages\x12\\\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x42.cloud.planton.apis.copilot.copilotchat.chatmessage.v1.ChatMessageR\x07\x65ntries\"-\n\rChatSessionId\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"S\n\x19GetChatMessageStreamInput\x12\x17\n\x07\x63hat_id\x18\x01 \x01(\tR\x06\x63hatId\x12\x1d\n\nsession_id\x18\x02 \x01(\tR\tsessionId\"A\n-ChatMessagesCountCurrentAndPreviousMonthInput\x12\x10\n\x03org\x18\x01 \x01(\tR\x03org\"\x8c\x01\n(ChatMessagesCountCurrentAndPreviousMonth\x12.\n\x13\x63urrent_month_count\x18\x01 \x01(\x01R\x11\x63urrentMonthCount\x12\x30\n\x14previous_month_count\x18\x02 \x01(\x01R\x12previousMonthCountB\xc1\x02\n9com.cloud.planton.apis.copilot.copilotchat.chatmessage.v1B\x07IoProtoP\x01\xa2\x02\x06\x43PACCC\xaa\x02\x35\x43loud.Planton.Apis.Copilot.Copilotchat.Chatmessage.V1\xca\x02\x35\x43loud\\Planton\\Apis\\Copilot\\Copilotchat\\Chatmessage\\V1\xe2\x02\x41\x43loud\\Planton\\Apis\\Copilot\\Copilotchat\\Chatmessage\\V1\\GPBMetadata\xea\x02;Cloud::Planton::Apis::Copilot::Copilotchat::Chatmessage::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.copilot.copilotchat.chatmessage.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n9com.cloud.planton.apis.copilot.copilotchat.chatmessage.v1B\007IoProtoP\001\242\002\006CPACCC\252\0025Cloud.Planton.Apis.Copilot.Copilotchat.Chatmessage.V1\312\0025Cloud\\Planton\\Apis\\Copilot\\Copilotchat\\Chatmessage\\V1\342\002ACloud\\Planton\\Apis\\Copilot\\Copilotchat\\Chatmessage\\V1\\GPBMetadata\352\002;Cloud::Planton::Apis::Copilot::Copilotchat::Chatmessage::V1'
  _globals['_CHATMESSAGEID'].fields_by_name['value']._loaded_options = None
  _globals['_CHATMESSAGEID'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CHATSESSIONID'].fields_by_name['value']._loaded_options = None
  _globals['_CHATSESSIONID'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CHATMESSAGEID']._serialized_start=215
  _globals['_CHATMESSAGEID']._serialized_end=260
  _globals['_SENDMESSAGEINPUT']._serialized_start=262
  _globals['_SENDMESSAGEINPUT']._serialized_end=331
  _globals['_CHATMESSAGES']._serialized_start=333
  _globals['_CHATMESSAGES']._serialized_end=441
  _globals['_CHATSESSIONID']._serialized_start=443
  _globals['_CHATSESSIONID']._serialized_end=488
  _globals['_GETCHATMESSAGESTREAMINPUT']._serialized_start=490
  _globals['_GETCHATMESSAGESTREAMINPUT']._serialized_end=573
  _globals['_CHATMESSAGESCOUNTCURRENTANDPREVIOUSMONTHINPUT']._serialized_start=575
  _globals['_CHATMESSAGESCOUNTCURRENTANDPREVIOUSMONTHINPUT']._serialized_end=640
  _globals['_CHATMESSAGESCOUNTCURRENTANDPREVIOUSMONTH']._serialized_start=643
  _globals['_CHATMESSAGESCOUNTCURRENTANDPREVIOUSMONTH']._serialized_end=783
# @@protoc_insertion_point(module_scope)
