# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/kubernetes/workload/temporalkubernetes/v1/stack_input.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/kubernetes/workload/temporalkubernetes/v1/stack_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from project.planton.provider.kubernetes import provider_pb2 as project_dot_planton_dot_provider_dot_kubernetes_dot_provider__pb2
from project.planton.provider.kubernetes.workload.temporalkubernetes.v1 import api_pb2 as project_dot_planton_dot_provider_dot_kubernetes_dot_workload_dot_temporalkubernetes_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTproject/planton/provider/kubernetes/workload/temporalkubernetes/v1/stack_input.proto\x12\x42project.planton.provider.kubernetes.workload.temporalkubernetes.v1\x1a\x32project/planton/provider/kubernetes/provider.proto\x1aLproject/planton/provider/kubernetes/workload/temporalkubernetes/v1/api.proto\"\xa9\x02\n\x1cTemporalKubernetesStackInput\x12n\n\x06target\x18\x01 \x01(\x0b\x32V.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesR\x06target\x12\x66\n\x0fprovider_config\x18\x02 \x01(\x0b\x32=.project.planton.provider.kubernetes.KubernetesProviderConfigR\x0eproviderConfig\x12\x31\n\x14kubernetes_namespace\x18\x03 \x01(\tR\x13kubernetesNamespaceB\x8a\x03\nFcom.project.planton.provider.kubernetes.workload.temporalkubernetes.v1B\x0fStackInputProtoP\x01\xa2\x02\x06PPPKWT\xaa\x02\x42Project.Planton.Provider.Kubernetes.Workload.Temporalkubernetes.V1\xca\x02\x42Project\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\xe2\x02NProject\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\\GPBMetadata\xea\x02HProject::Planton::Provider::Kubernetes::Workload::Temporalkubernetes::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.kubernetes.workload.temporalkubernetes.v1.stack_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nFcom.project.planton.provider.kubernetes.workload.temporalkubernetes.v1B\017StackInputProtoP\001\242\002\006PPPKWT\252\002BProject.Planton.Provider.Kubernetes.Workload.Temporalkubernetes.V1\312\002BProject\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\342\002NProject\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\\GPBMetadata\352\002HProject::Planton::Provider::Kubernetes::Workload::Temporalkubernetes::V1'
  _globals['_TEMPORALKUBERNETESSTACKINPUT']._serialized_start=287
  _globals['_TEMPORALKUBERNETESSTACKINPUT']._serialized_end=584
# @@protoc_insertion_point(module_scope)
