# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/kubernetes/workload/gitlabkubernetes/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/kubernetes/workload/gitlabkubernetes/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from project.planton.provider.kubernetes.workload.gitlabkubernetes.v1 import spec_pb2 as project_dot_planton_dot_provider_dot_kubernetes_dot_workload_dot_gitlabkubernetes_dot_v1_dot_spec__pb2
from project.planton.provider.kubernetes.workload.gitlabkubernetes.v1 import stack_outputs_pb2 as project_dot_planton_dot_provider_dot_kubernetes_dot_workload_dot_gitlabkubernetes_dot_v1_dot_stack__outputs__pb2
from project.planton.shared import metadata_pb2 as project_dot_planton_dot_shared_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJproject/planton/provider/kubernetes/workload/gitlabkubernetes/v1/api.proto\x12@project.planton.provider.kubernetes.workload.gitlabkubernetes.v1\x1a\x1b\x62uf/validate/validate.proto\x1aKproject/planton/provider/kubernetes/workload/gitlabkubernetes/v1/spec.proto\x1aTproject/planton/provider/kubernetes/workload/gitlabkubernetes/v1/stack_outputs.proto\x1a%project/planton/shared/metadata.proto\"\xc3\x03\n\x10GitlabKubernetes\x12I\n\x0b\x61pi_version\x18\x01 \x01(\tB(\xbaH%r#\n!kubernetes.project-planton.org/v1R\napiVersion\x12+\n\x04kind\x18\x02 \x01(\tB\x17\xbaH\x14r\x12\n\x10GitlabKubernetesR\x04kind\x12Q\n\x08metadata\x18\x03 \x01(\x0b\x32-.project.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\x08metadata\x12r\n\x04spec\x18\x04 \x01(\x0b\x32V.project.planton.provider.kubernetes.workload.gitlabkubernetes.v1.GitlabKubernetesSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12p\n\x06status\x18\x05 \x01(\x0b\x32X.project.planton.provider.kubernetes.workload.gitlabkubernetes.v1.GitlabKubernetesStatusR\x06status\"\x92\x01\n\x16GitlabKubernetesStatus\x12x\n\x07outputs\x18\x01 \x01(\x0b\x32^.project.planton.provider.kubernetes.workload.gitlabkubernetes.v1.GitlabKubernetesStackOutputsR\x07outputsB\xf9\x02\nDcom.project.planton.provider.kubernetes.workload.gitlabkubernetes.v1B\x08\x41piProtoP\x01\xa2\x02\x06PPPKWG\xaa\x02@Project.Planton.Provider.Kubernetes.Workload.Gitlabkubernetes.V1\xca\x02@Project\\Planton\\Provider\\Kubernetes\\Workload\\Gitlabkubernetes\\V1\xe2\x02LProject\\Planton\\Provider\\Kubernetes\\Workload\\Gitlabkubernetes\\V1\\GPBMetadata\xea\x02\x46Project::Planton::Provider::Kubernetes::Workload::Gitlabkubernetes::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.kubernetes.workload.gitlabkubernetes.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nDcom.project.planton.provider.kubernetes.workload.gitlabkubernetes.v1B\010ApiProtoP\001\242\002\006PPPKWG\252\002@Project.Planton.Provider.Kubernetes.Workload.Gitlabkubernetes.V1\312\002@Project\\Planton\\Provider\\Kubernetes\\Workload\\Gitlabkubernetes\\V1\342\002LProject\\Planton\\Provider\\Kubernetes\\Workload\\Gitlabkubernetes\\V1\\GPBMetadata\352\002FProject::Planton::Provider::Kubernetes::Workload::Gitlabkubernetes::V1'
  _globals['_GITLABKUBERNETES'].fields_by_name['api_version']._loaded_options = None
  _globals['_GITLABKUBERNETES'].fields_by_name['api_version']._serialized_options = b'\272H%r#\n!kubernetes.project-planton.org/v1'
  _globals['_GITLABKUBERNETES'].fields_by_name['kind']._loaded_options = None
  _globals['_GITLABKUBERNETES'].fields_by_name['kind']._serialized_options = b'\272H\024r\022\n\020GitlabKubernetes'
  _globals['_GITLABKUBERNETES'].fields_by_name['metadata']._loaded_options = None
  _globals['_GITLABKUBERNETES'].fields_by_name['metadata']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITLABKUBERNETES'].fields_by_name['spec']._loaded_options = None
  _globals['_GITLABKUBERNETES'].fields_by_name['spec']._serialized_options = b'\272H\003\310\001\001'
  _globals['_GITLABKUBERNETES']._serialized_start=376
  _globals['_GITLABKUBERNETES']._serialized_end=827
  _globals['_GITLABKUBERNETESSTATUS']._serialized_start=830
  _globals['_GITLABKUBERNETESSTATUS']._serialized_end=976
# @@protoc_insertion_point(module_scope)
