# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/connect/npmcredential/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/connect/npmcredential/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.commons.apiresource import metadata_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_metadata__pb2
from cloud.planton.apis.commons.apiresource import status_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_status__pb2
from cloud.planton.apis.connect.npmcredential.v1 import spec_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_npmcredential_dot_v1_dot_spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cloud/planton/apis/connect/npmcredential/v1/api.proto\x12+cloud.planton.apis.connect.npmcredential.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x35\x63loud/planton/apis/commons/apiresource/metadata.proto\x1a\x33\x63loud/planton/apis/commons/apiresource/status.proto\x1a\x36\x63loud/planton/apis/connect/npmcredential/v1/spec.proto\"\x85\x03\n\rNpmCredential\x12=\n\x0b\x61pi_version\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\n\x15\x63onnect.planton.ai/v1R\napiVersion\x12(\n\x04kind\x18\x02 \x01(\tB\x14\xbaH\x11r\x0f\n\rNpmCredentialR\x04kind\x12_\n\x08metadata\x18\x03 \x01(\x0b\x32;.cloud.planton.apis.commons.apiresource.ApiResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\x08metadata\x12R\n\x04spec\x18\x04 \x01(\x0b\x32>.cloud.planton.apis.connect.npmcredential.v1.NpmCredentialSpecR\x04spec\x12V\n\x06status\x18\x05 \x01(\x0b\x32>.cloud.planton.apis.commons.apiresource.ApiResourceAuditStatusR\x06statusB\x8e\x02\n/com.cloud.planton.apis.connect.npmcredential.v1B\x08\x41piProtoP\x01\xa2\x02\x05\x43PACN\xaa\x02+Cloud.Planton.Apis.Connect.Npmcredential.V1\xca\x02+Cloud\\Planton\\Apis\\Connect\\Npmcredential\\V1\xe2\x02\x37\x43loud\\Planton\\Apis\\Connect\\Npmcredential\\V1\\GPBMetadata\xea\x02\x30\x43loud::Planton::Apis::Connect::Npmcredential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.connect.npmcredential.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.cloud.planton.apis.connect.npmcredential.v1B\010ApiProtoP\001\242\002\005CPACN\252\002+Cloud.Planton.Apis.Connect.Npmcredential.V1\312\002+Cloud\\Planton\\Apis\\Connect\\Npmcredential\\V1\342\0027Cloud\\Planton\\Apis\\Connect\\Npmcredential\\V1\\GPBMetadata\352\0020Cloud::Planton::Apis::Connect::Npmcredential::V1'
  _globals['_NPMCREDENTIAL'].fields_by_name['api_version']._loaded_options = None
  _globals['_NPMCREDENTIAL'].fields_by_name['api_version']._serialized_options = b'\272H\031r\027\n\025connect.planton.ai/v1'
  _globals['_NPMCREDENTIAL'].fields_by_name['kind']._loaded_options = None
  _globals['_NPMCREDENTIAL'].fields_by_name['kind']._serialized_options = b'\272H\021r\017\n\rNpmCredential'
  _globals['_NPMCREDENTIAL'].fields_by_name['metadata']._loaded_options = None
  _globals['_NPMCREDENTIAL'].fields_by_name['metadata']._serialized_options = b'\272H\003\310\001\001'
  _globals['_NPMCREDENTIAL']._serialized_start=296
  _globals['_NPMCREDENTIAL']._serialized_end=685
# @@protoc_insertion_point(module_scope)
