# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/kubeops/v1/podexec/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/kubeops/v1/podexec/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.integration.kubernetes.kubernetesobject import io_pb2 as cloud_dot_planton_dot_apis_dot_integration_dot_kubernetes_dot_kubernetesobject_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.cloud/planton/apis/kubeops/v1/podexec/io.proto\x12%cloud.planton.apis.kubeops.v1.podexec\x1a\x43\x63loud/planton/apis/integration/kubernetes/kubernetesobject/io.proto\"\xb6\x01\n\x19\x45xecIntoPodContainerInput\x12*\n\x11\x63loud_resource_id\x18\x01 \x01(\tR\x0f\x63loudResourceId\x12m\n\x07options\x18\x02 \x01(\x0b\x32S.cloud.planton.apis.integration.kubernetes.kubernetesobject.PodContainerExecOptionsR\x07options\"\xd5\x01\n#BrowserExecIntoPodContainerResponse\x12(\n\x10shell_session_id\x18\x01 \x01(\tR\x0eshellSessionId\x12\x83\x01\n\x10\x63ommand_response\x18\x02 \x01(\x0b\x32X.cloud.planton.apis.integration.kubernetes.kubernetesobject.ExecIntoPodContainerResponseR\x0f\x63ommandResponse\"\x9e\x01\n,BrowserExecuteNextCommandInPodContainerInput\x12*\n\x11\x63loud_resource_id\x18\x01 \x01(\tR\x0f\x63loudResourceId\x12(\n\x10shell_session_id\x18\x02 \x01(\tR\x0eshellSessionId\x12\x18\n\x07\x63ommand\x18\x03 \x01(\tR\x07\x63ommandB\xf0\x01\n)com.cloud.planton.apis.kubeops.v1.podexecB\x07IoProtoP\x01\xa2\x02\x06\x43PAKVP\xaa\x02%Cloud.Planton.Apis.Kubeops.V1.Podexec\xca\x02%Cloud\\Planton\\Apis\\Kubeops\\V1\\Podexec\xe2\x02\x31\x43loud\\Planton\\Apis\\Kubeops\\V1\\Podexec\\GPBMetadata\xea\x02*Cloud::Planton::Apis::Kubeops::V1::Podexecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.kubeops.v1.podexec.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.cloud.planton.apis.kubeops.v1.podexecB\007IoProtoP\001\242\002\006CPAKVP\252\002%Cloud.Planton.Apis.Kubeops.V1.Podexec\312\002%Cloud\\Planton\\Apis\\Kubeops\\V1\\Podexec\342\0021Cloud\\Planton\\Apis\\Kubeops\\V1\\Podexec\\GPBMetadata\352\002*Cloud::Planton::Apis::Kubeops::V1::Podexec'
  _globals['_EXECINTOPODCONTAINERINPUT']._serialized_start=159
  _globals['_EXECINTOPODCONTAINERINPUT']._serialized_end=341
  _globals['_BROWSEREXECINTOPODCONTAINERRESPONSE']._serialized_start=344
  _globals['_BROWSEREXECINTOPODCONTAINERRESPONSE']._serialized_end=557
  _globals['_BROWSEREXECUTENEXTCOMMANDINPODCONTAINERINPUT']._serialized_start=560
  _globals['_BROWSEREXECUTENEXTCOMMANDINPODCONTAINERINPUT']._serialized_end=718
# @@protoc_insertion_point(module_scope)
