# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/infraproject/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/infraproject/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.infrahub.infraproject.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_infraproject_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4cloud/planton/apis/infrahub/infraproject/v1/io.proto\x12+cloud.planton.apis.infrahub.infraproject.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x35\x63loud/planton/apis/infrahub/infraproject/v1/api.proto\".\n\x0eInfraProjectId\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"\x88\x01\n\x10InfraProjectList\x12\x1f\n\x0btotal_pages\x18\x01 \x01(\x05R\ntotalPages\x12S\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x39.cloud.planton.apis.infrahub.infraproject.v1.InfraProjectR\x07\x65ntriesB\x8d\x02\n/com.cloud.planton.apis.infrahub.infraproject.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02+Cloud.Planton.Apis.Infrahub.Infraproject.V1\xca\x02+Cloud\\Planton\\Apis\\Infrahub\\Infraproject\\V1\xe2\x02\x37\x43loud\\Planton\\Apis\\Infrahub\\Infraproject\\V1\\GPBMetadata\xea\x02\x30\x43loud::Planton::Apis::Infrahub::Infraproject::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.infraproject.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.cloud.planton.apis.infrahub.infraproject.v1B\007IoProtoP\001\242\002\005CPAII\252\002+Cloud.Planton.Apis.Infrahub.Infraproject.V1\312\002+Cloud\\Planton\\Apis\\Infrahub\\Infraproject\\V1\342\0027Cloud\\Planton\\Apis\\Infrahub\\Infraproject\\V1\\GPBMetadata\352\0020Cloud::Planton::Apis::Infrahub::Infraproject::V1'
  _globals['_INFRAPROJECTID'].fields_by_name['value']._loaded_options = None
  _globals['_INFRAPROJECTID'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_INFRAPROJECTID']._serialized_start=185
  _globals['_INFRAPROJECTID']._serialized_end=231
  _globals['_INFRAPROJECTLIST']._serialized_start=234
  _globals['_INFRAPROJECTLIST']._serialized_end=370
# @@protoc_insertion_point(module_scope)
