# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/stackjob/v1/terraform/enum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/stackjob/v1/terraform/enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<cloud/planton/apis/infrahub/stackjob/v1/terraform/enum.proto\x12\x31\x63loud.planton.apis.infrahub.stackjob.v1.terraform*\xd1\x01\n\x1cTerraformEngineOperationType\x12/\n+terraform_engine_operation_type_unspecified\x10\x00\x12\x08\n\x04noop\x10\x01\x12\n\n\x06\x63reate\x10\x02\x12\x08\n\x04read\x10\x03\x12\n\n\x06update\x10\x04\x12\n\n\x06\x64\x65lete\x10\x05\x12\x0b\n\x07replace\x10\x06\x12\x08\n\x04move\x10\x07\x12\x18\n\x14\x63hange_action_import\x10\x08\x12\n\n\x06remove\x10\t\x12\x0b\n\x07refresh\x10\n*\x99\x04\n\x18TerraformEngineEventType\x12+\n\'terraform_engine_event_type_unspecified\x10\x00\x12\x0e\n\nplan_start\x10\x01\x12\x11\n\rplan_complete\x10\x02\x12\x10\n\x0cplan_errored\x10\x03\x12\x0f\n\x0b\x61pply_start\x10\x04\x12\x12\n\x0e\x61pply_complete\x10\x05\x12\x11\n\rapply_errored\x10\x06\x12\x11\n\rrefresh_start\x10\x07\x12\x14\n\x10refresh_complete\x10\x08\x12\x13\n\x0frefresh_errored\x10\t\x12\x17\n\x13\x63ost_estimate_start\x10\n\x12\x1a\n\x16\x63ost_estimate_complete\x10\x0b\x12\x19\n\x15\x63ost_estimate_errored\x10\x0c\x12\x11\n\rdestroy_start\x10\r\x12\x14\n\x10\x64\x65stroy_complete\x10\x0e\x12\x13\n\x0f\x64\x65stroy_errored\x10\x0f\x12\x08\n\x04step\x10\x10\x12\x0b\n\x07version\x10\x11\x12\x0e\n\ndiagnostic\x10\x12\x12\n\n\x06output\x10\x13\x12\x07\n\x03log\x10\x14\x12\x12\n\x0eplanned_change\x10\x15\x12\x12\n\x0e\x63hange_summary\x10\x16\x12\x12\n\x0e\x61pply_progress\x10\x17\x12\x12\n\x0eresource_drift\x10\x18\x12\x0b\n\x07outputs\x10\x19\x42\xb0\x02\n5com.cloud.planton.apis.infrahub.stackjob.v1.terraformB\tEnumProtoP\x01\xa2\x02\x07\x43PAISVT\xaa\x02\x31\x43loud.Planton.Apis.Infrahub.Stackjob.V1.Terraform\xca\x02\x31\x43loud\\Planton\\Apis\\Infrahub\\Stackjob\\V1\\Terraform\xe2\x02=Cloud\\Planton\\Apis\\Infrahub\\Stackjob\\V1\\Terraform\\GPBMetadata\xea\x02\x37\x43loud::Planton::Apis::Infrahub::Stackjob::V1::Terraformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.stackjob.v1.terraform.enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.cloud.planton.apis.infrahub.stackjob.v1.terraformB\tEnumProtoP\001\242\002\007CPAISVT\252\0021Cloud.Planton.Apis.Infrahub.Stackjob.V1.Terraform\312\0021Cloud\\Planton\\Apis\\Infrahub\\Stackjob\\V1\\Terraform\342\002=Cloud\\Planton\\Apis\\Infrahub\\Stackjob\\V1\\Terraform\\GPBMetadata\352\0027Cloud::Planton::Apis::Infrahub::Stackjob::V1::Terraform'
  _globals['_TERRAFORMENGINEOPERATIONTYPE']._serialized_start=116
  _globals['_TERRAFORMENGINEOPERATIONTYPE']._serialized_end=325
  _globals['_TERRAFORMENGINEEVENTTYPE']._serialized_start=328
  _globals['_TERRAFORMENGINEEVENTTYPE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
