# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/copilot/copilotagent/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/copilot/copilotagent/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource.apiresourcekind import api_resource_kind_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_apiresourcekind_dot_api__resource__kind__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3cloud/planton/apis/copilot/copilotagent/v1/io.proto\x12*cloud.planton.apis.copilot.copilotagent.v1\x1aNcloud/planton/apis/commons/apiresource/apiresourcekind/api_resource_kind.proto\"\xf6\x01\n\x13LoadSpecVectorInput\x12\x36\n\x17project_planton_version\x18\x01 \x01(\tR\x15projectPlantonVersion\x12\x32\n\x15planton_cloud_version\x18\x02 \x01(\tR\x13plantonCloudVersion\x12s\n\x11\x61pi_resource_kind\x18\x03 \x01(\x0e\x32G.cloud.planton.apis.commons.apiresource.apiresourcekind.ApiResourceKindR\x0f\x61piResourceKind\"2\n\x17GenerateChatNameRequest\x12\x17\n\x07\x63hat_id\x18\x01 \x01(\tR\x06\x63hatId\"A\n\x18GenerateChatNameResponse\x12%\n\x0esuggested_name\x18\x01 \x01(\tR\rsuggestedNameB\x88\x02\n.com.cloud.planton.apis.copilot.copilotagent.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PACC\xaa\x02*Cloud.Planton.Apis.Copilot.Copilotagent.V1\xca\x02*Cloud\\Planton\\Apis\\Copilot\\Copilotagent\\V1\xe2\x02\x36\x43loud\\Planton\\Apis\\Copilot\\Copilotagent\\V1\\GPBMetadata\xea\x02/Cloud::Planton::Apis::Copilot::Copilotagent::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.copilot.copilotagent.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.cloud.planton.apis.copilot.copilotagent.v1B\007IoProtoP\001\242\002\005CPACC\252\002*Cloud.Planton.Apis.Copilot.Copilotagent.V1\312\002*Cloud\\Planton\\Apis\\Copilot\\Copilotagent\\V1\342\0026Cloud\\Planton\\Apis\\Copilot\\Copilotagent\\V1\\GPBMetadata\352\002/Cloud::Planton::Apis::Copilot::Copilotagent::V1'
  _globals['_LOADSPECVECTORINPUT']._serialized_start=180
  _globals['_LOADSPECVECTORINPUT']._serialized_end=426
  _globals['_GENERATECHATNAMEREQUEST']._serialized_start=428
  _globals['_GENERATECHATNAMEREQUEST']._serialized_end=478
  _globals['_GENERATECHATNAMERESPONSE']._serialized_start=480
  _globals['_GENERATECHATNAMERESPONSE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
