# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/audit/apiresourceversion/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/audit/apiresourceversion/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.audit.apiresourceversion.v1 import spec_pb2 as cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_spec__pb2
from cloud.planton.apis.commons.apiresource import metadata_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_metadata__pb2
from cloud.planton.apis.commons.apiresource import status_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_status__pb2
from cloud.planton.apis.commons.workflow import workflow_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_workflow_dot_workflow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8cloud/planton/apis/audit/apiresourceversion/v1/api.proto\x12.cloud.planton.apis.audit.apiresourceversion.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x39\x63loud/planton/apis/audit/apiresourceversion/v1/spec.proto\x1a\x35\x63loud/planton/apis/commons/apiresource/metadata.proto\x1a\x33\x63loud/planton/apis/commons/apiresource/status.proto\x1a\x32\x63loud/planton/apis/commons/workflow/workflow.proto\"\x97\x03\n\x12\x41piResourceVersion\x12;\n\x0b\x61pi_version\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\n\x13\x61udit.planton.ai/v1R\napiVersion\x12-\n\x04kind\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\n\x12\x41piResourceVersionR\x04kind\x12W\n\x08metadata\x18\x03 \x01(\x0b\x32;.cloud.planton.apis.commons.apiresource.ApiResourceMetadataR\x08metadata\x12Z\n\x04spec\x18\x04 \x01(\x0b\x32\x46.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionSpecR\x04spec\x12`\n\x06status\x18\x05 \x01(\x0b\x32H.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionStatusR\x06status\"\xdc\x02\n\x18\x41piResourceVersionStatus\x12N\n\x05\x61udit\x18\x63 \x01(\x0b\x32\x38.cloud.planton.apis.commons.apiresource.ApiResourceAuditR\x05\x61udit\x12w\n\x19stack_job_progress_status\x18\x01 \x01(\x0e\x32<.cloud.planton.apis.commons.workflow.WorkflowExecutionStatusR\x16stackJobProgressStatus\x12w\n\x19stack_job_progress_result\x18\x02 \x01(\x0e\x32<.cloud.planton.apis.commons.workflow.WorkflowExecutionResultR\x16stackJobProgressResultB\x9d\x02\n2com.cloud.planton.apis.audit.apiresourceversion.v1B\x08\x41piProtoP\x01\xa2\x02\x05\x43PAAA\xaa\x02.Cloud.Planton.Apis.Audit.Apiresourceversion.V1\xca\x02.Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\xe2\x02:Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\\GPBMetadata\xea\x02\x33\x43loud::Planton::Apis::Audit::Apiresourceversion::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.audit.apiresourceversion.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.cloud.planton.apis.audit.apiresourceversion.v1B\010ApiProtoP\001\242\002\005CPAAA\252\002.Cloud.Planton.Apis.Audit.Apiresourceversion.V1\312\002.Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\342\002:Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\\GPBMetadata\352\0023Cloud::Planton::Apis::Audit::Apiresourceversion::V1'
  _globals['_APIRESOURCEVERSION'].fields_by_name['api_version']._loaded_options = None
  _globals['_APIRESOURCEVERSION'].fields_by_name['api_version']._serialized_options = b'\272H\027r\025\n\023audit.planton.ai/v1'
  _globals['_APIRESOURCEVERSION'].fields_by_name['kind']._loaded_options = None
  _globals['_APIRESOURCEVERSION'].fields_by_name['kind']._serialized_options = b'\272H\026r\024\n\022ApiResourceVersion'
  _globals['_APIRESOURCEVERSION']._serialized_start=357
  _globals['_APIRESOURCEVERSION']._serialized_end=764
  _globals['_APIRESOURCEVERSIONSTATUS']._serialized_start=767
  _globals['_APIRESOURCEVERSIONSTATUS']._serialized_end=1115
# @@protoc_insertion_point(module_scope)
