# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/audit/apiresourceversion/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/audit/apiresourceversion/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.audit.apiresourceversion.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2
from cloud.planton.apis.audit.apiresourceversion.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:cloud/planton/apis/audit/apiresourceversion/v1/query.proto\x12.cloud.planton.apis.audit.apiresourceversion.v1\x1a\x38\x63loud/planton/apis/audit/apiresourceversion/v1/api.proto\x1a\x37\x63loud/planton/apis/audit/apiresourceversion/v1/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto2\xc1\x05\n!ApiResourceVersionQueryController\x12\x8f\x01\n\x03get\x12\x44.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionId\x1a\x42.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersion\x12\xa5\x01\n\rlistByFilters\x12L.cloud.planton.apis.audit.apiresourceversion.v1.ListApiResourceVersionsInput\x1a\x46.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionList\x12\xb4\x01\n\x16getByIdWithContextSize\x12V.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionWithContextSizeInput\x1a\x42.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersion\x12\xa4\x01\n\x08getCount\x12O.cloud.planton.apis.audit.apiresourceversion.v1.GetApiResourceVersionCountInput\x1aG.cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionCount\x1a\x04\xa0\xff+\x14\x42\x9f\x02\n2com.cloud.planton.apis.audit.apiresourceversion.v1B\nQueryProtoP\x01\xa2\x02\x05\x43PAAA\xaa\x02.Cloud.Planton.Apis.Audit.Apiresourceversion.V1\xca\x02.Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\xe2\x02:Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\\GPBMetadata\xea\x02\x33\x43loud::Planton::Apis::Audit::Apiresourceversion::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.audit.apiresourceversion.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.cloud.planton.apis.audit.apiresourceversion.v1B\nQueryProtoP\001\242\002\005CPAAA\252\002.Cloud.Planton.Apis.Audit.Apiresourceversion.V1\312\002.Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\342\002:Cloud\\Planton\\Apis\\Audit\\Apiresourceversion\\V1\\GPBMetadata\352\0023Cloud::Planton::Apis::Audit::Apiresourceversion::V1'
  _globals['_APIRESOURCEVERSIONQUERYCONTROLLER']._loaded_options = None
  _globals['_APIRESOURCEVERSIONQUERYCONTROLLER']._serialized_options = b'\240\377+\024'
  _globals['_APIRESOURCEVERSIONQUERYCONTROLLER']._serialized_start=292
  _globals['_APIRESOURCEVERSIONQUERYCONTROLLER']._serialized_end=997
# @@protoc_insertion_point(module_scope)
