# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.audit.apiresourceversion.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2
from cloud.planton.apis.audit.apiresourceversion.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2


class ApiResourceVersionQueryControllerStub(object):
    """api-resource-version query controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/get',
                request_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionId.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.FromString,
                _registered_method=True)
        self.listByFilters = channel.unary_unary(
                '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/listByFilters',
                request_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ListApiResourceVersionsInput.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionList.FromString,
                _registered_method=True)
        self.getByIdWithContextSize = channel.unary_unary(
                '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/getByIdWithContextSize',
                request_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionWithContextSizeInput.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.FromString,
                _registered_method=True)
        self.getCount = channel.unary_unary(
                '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/getCount',
                request_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.GetApiResourceVersionCountInput.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionCount.FromString,
                _registered_method=True)


class ApiResourceVersionQueryControllerServicer(object):
    """api-resource-version query controller
    """

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listByFilters(self, request, context):
        """list of api-resource-versions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getByIdWithContextSize(self, request, context):
        """look up api-resource-version by version-id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCount(self, request, context):
        """count of api-resource-versions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiResourceVersionQueryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionId.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.SerializeToString,
            ),
            'listByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.listByFilters,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ListApiResourceVersionsInput.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionList.SerializeToString,
            ),
            'getByIdWithContextSize': grpc.unary_unary_rpc_method_handler(
                    servicer.getByIdWithContextSize,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionWithContextSizeInput.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.SerializeToString,
            ),
            'getCount': grpc.unary_unary_rpc_method_handler(
                    servicer.getCount,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.GetApiResourceVersionCountInput.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiResourceVersionQueryController(object):
    """api-resource-version query controller
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/get',
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionId.SerializeToString,
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/listByFilters',
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ListApiResourceVersionsInput.SerializeToString,
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getByIdWithContextSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/getByIdWithContextSize',
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionWithContextSizeInput.SerializeToString,
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_api__pb2.ApiResourceVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.audit.apiresourceversion.v1.ApiResourceVersionQueryController/getCount',
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.GetApiResourceVersionCountInput.SerializeToString,
            cloud_dot_planton_dot_apis_dot_audit_dot_apiresourceversion_dot_v1_dot_io__pb2.ApiResourceVersionCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
