# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/infrachart/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/infrachart/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import find_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_find__pb2
from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.infrahub.infrachart.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_infrachart_dot_v1_dot_api__pb2
from cloud.planton.apis.infrahub.infrachart.v1 import io_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_infrachart_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cloud/planton/apis/infrahub/infrachart/v1/query.proto\x12)cloud.planton.apis.infrahub.infrachart.v1\x1a\x31\x63loud/planton/apis/commons/apiresource/find.proto\x1a/cloud/planton/apis/commons/apiresource/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1a\x33\x63loud/planton/apis/infrahub/infrachart/v1/api.proto\x1a\x32\x63loud/planton/apis/infrahub/infrachart/v1/io.proto2\xc5\x03\n\x19InfraChartQueryController\x12s\n\x03get\x12\x35.cloud.planton.apis.commons.apiresource.ApiResourceId\x1a\x35.cloud.planton.apis.infrahub.infrachart.v1.InfraChart\x12{\n\x05\x62uild\x12\x35.cloud.planton.apis.infrahub.infrachart.v1.InfraChart\x1a\x35.cloud.planton.apis.infrahub.infrachart.v1.InfraChart\"\x04\xd0\xb8\x18\x01\x12\xaf\x01\n\x04\x66ind\x12?.cloud.planton.apis.commons.apiresource.FindApiResourcesRequest\x1a\x39.cloud.planton.apis.infrahub.infrachart.v1.InfraChartList\"+\xc2\xb8\x18\'\x08\x08\x10\x0b*!unauthorized to find infra-charts\x1a\x04\xa0\xff+$B\x86\x02\n-com.cloud.planton.apis.infrahub.infrachart.v1B\nQueryProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02)Cloud.Planton.Apis.Infrahub.Infrachart.V1\xca\x02)Cloud\\Planton\\Apis\\Infrahub\\Infrachart\\V1\xe2\x02\x35\x43loud\\Planton\\Apis\\Infrahub\\Infrachart\\V1\\GPBMetadata\xea\x02.Cloud::Planton::Apis::Infrahub::Infrachart::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.infrachart.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.cloud.planton.apis.infrahub.infrachart.v1B\nQueryProtoP\001\242\002\005CPAII\252\002)Cloud.Planton.Apis.Infrahub.Infrachart.V1\312\002)Cloud\\Planton\\Apis\\Infrahub\\Infrachart\\V1\342\0025Cloud\\Planton\\Apis\\Infrahub\\Infrachart\\V1\\GPBMetadata\352\002.Cloud::Planton::Apis::Infrahub::Infrachart::V1'
  _globals['_INFRACHARTQUERYCONTROLLER']._loaded_options = None
  _globals['_INFRACHARTQUERYCONTROLLER']._serialized_options = b'\240\377+$'
  _globals['_INFRACHARTQUERYCONTROLLER'].methods_by_name['build']._loaded_options = None
  _globals['_INFRACHARTQUERYCONTROLLER'].methods_by_name['build']._serialized_options = b'\320\270\030\001'
  _globals['_INFRACHARTQUERYCONTROLLER'].methods_by_name['find']._loaded_options = None
  _globals['_INFRACHARTQUERYCONTROLLER'].methods_by_name['find']._serialized_options = b'\302\270\030\'\010\010\020\013*!unauthorized to find infra-charts'
  _globals['_INFRACHARTQUERYCONTROLLER']._serialized_start=447
  _globals['_INFRACHARTQUERYCONTROLLER']._serialized_end=900
# @@protoc_insertion_point(module_scope)
