# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/servicehub/dnsdomain/v1/command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/servicehub/dnsdomain/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.commons.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_io__pb2
from cloud.planton.apis.commons.apiresource import rpc_service_options_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from cloud.planton.apis.iam.iampolicy.v1.rpcauthorization import method_options_pb2 as cloud_dot_planton_dot_apis_dot_iam_dot_iampolicy_dot_v1_dot_rpcauthorization_dot_method__options__pb2
from cloud.planton.apis.servicehub.dnsdomain.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_servicehub_dot_dnsdomain_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8cloud/planton/apis/servicehub/dnsdomain/v1/command.proto\x12*cloud.planton.apis.servicehub.dnsdomain.v1\x1a/cloud/planton/apis/commons/apiresource/io.proto\x1a@cloud/planton/apis/commons/apiresource/rpc_service_options.proto\x1aIcloud/planton/apis/iam/iampolicy/v1/rpcauthorization/method_options.proto\x1a\x34\x63loud/planton/apis/servicehub/dnsdomain/v1/api.proto2\xbc\x05\n\x1a\x44nsDomainCommandController\x12u\n\x05\x61pply\x12\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\x1a\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\x12\xb1\x01\n\x06\x63reate\x12\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\x1a\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\"9\xc2\xb8\x18\x35\x08\x14\x10\r\"\x0cmetadata.org*!unauthorized to create dns-domain\x12\xb0\x01\n\x06update\x12\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\x1a\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\"8\xc2\xb8\x18\x34\x08\x05\x10\x13\"\x0bmetadata.id*!unauthorized to update dns-domain\x12\xb9\x01\n\x06\x64\x65lete\x12>.cloud.planton.apis.commons.apiresource.ApiResourceDeleteInput\x1a\x35.cloud.planton.apis.servicehub.dnsdomain.v1.DnsDomain\"8\xc2\xb8\x18\x34\x08\x02\x10\x13\"\x0bresource_id*!unauthorized to delete dns-domain\x1a\x04\xa0\xff+\x13\x42\x8d\x02\n.com.cloud.planton.apis.servicehub.dnsdomain.v1B\x0c\x43ommandProtoP\x01\xa2\x02\x05\x43PASD\xaa\x02*Cloud.Planton.Apis.Servicehub.Dnsdomain.V1\xca\x02*Cloud\\Planton\\Apis\\Servicehub\\Dnsdomain\\V1\xe2\x02\x36\x43loud\\Planton\\Apis\\Servicehub\\Dnsdomain\\V1\\GPBMetadata\xea\x02/Cloud::Planton::Apis::Servicehub::Dnsdomain::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.servicehub.dnsdomain.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.cloud.planton.apis.servicehub.dnsdomain.v1B\014CommandProtoP\001\242\002\005CPASD\252\002*Cloud.Planton.Apis.Servicehub.Dnsdomain.V1\312\002*Cloud\\Planton\\Apis\\Servicehub\\Dnsdomain\\V1\342\0026Cloud\\Planton\\Apis\\Servicehub\\Dnsdomain\\V1\\GPBMetadata\352\002/Cloud::Planton::Apis::Servicehub::Dnsdomain::V1'
  _globals['_DNSDOMAINCOMMANDCONTROLLER']._loaded_options = None
  _globals['_DNSDOMAINCOMMANDCONTROLLER']._serialized_options = b'\240\377+\023'
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['create']._loaded_options = None
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['create']._serialized_options = b'\302\270\0305\010\024\020\r\"\014metadata.org*!unauthorized to create dns-domain'
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['update']._loaded_options = None
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['update']._serialized_options = b'\302\270\0304\010\005\020\023\"\013metadata.id*!unauthorized to update dns-domain'
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['delete']._loaded_options = None
  _globals['_DNSDOMAINCOMMANDCONTROLLER'].methods_by_name['delete']._serialized_options = b'\302\270\0304\010\002\020\023\"\013resource_id*!unauthorized to delete dns-domain'
  _globals['_DNSDOMAINCOMMANDCONTROLLER']._serialized_start=349
  _globals['_DNSDOMAINCOMMANDCONTROLLER']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
