# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/agentfleet/session/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/agentfleet/session/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.agentfleet.session.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_agentfleet_dot_session_dot_v1_dot_api__pb2
from cloud.planton.apis.commons.rpc import pagination_pb2 as cloud_dot_planton_dot_apis_dot_commons_dot_rpc_dot_pagination__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1cloud/planton/apis/agentfleet/session/v1/io.proto\x12(cloud.planton.apis.agentfleet.session.v1\x1a\x32\x63loud/planton/apis/agentfleet/session/v1/api.proto\x1a/cloud/planton/apis/commons/rpc/pagination.proto\"u\n\x11ListSessionsInput\x12\x45\n\tpage_info\x18\x01 \x01(\x0b\x32(.cloud.planton.apis.commons.rpc.PageInfoR\x08pageInfo\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\"\x9d\x01\n\x0bSessionList\x12G\n\x05items\x18\x01 \x03(\x0b\x32\x31.cloud.planton.apis.agentfleet.session.v1.SessionR\x05items\x12\x45\n\tpage_info\x18\x02 \x01(\x0b\x32(.cloud.planton.apis.commons.rpc.PageInfoR\x08pageInfoB\xfe\x01\n,com.cloud.planton.apis.agentfleet.session.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PAAS\xaa\x02(Cloud.Planton.Apis.Agentfleet.Session.V1\xca\x02(Cloud\\Planton\\Apis\\Agentfleet\\Session\\V1\xe2\x02\x34\x43loud\\Planton\\Apis\\Agentfleet\\Session\\V1\\GPBMetadata\xea\x02-Cloud::Planton::Apis::Agentfleet::Session::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.agentfleet.session.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.cloud.planton.apis.agentfleet.session.v1B\007IoProtoP\001\242\002\005CPAAS\252\002(Cloud.Planton.Apis.Agentfleet.Session.V1\312\002(Cloud\\Planton\\Apis\\Agentfleet\\Session\\V1\342\0024Cloud\\Planton\\Apis\\Agentfleet\\Session\\V1\\GPBMetadata\352\002-Cloud::Planton::Apis::Agentfleet::Session::V1'
  _globals['_LISTSESSIONSINPUT']._serialized_start=196
  _globals['_LISTSESSIONSINPUT']._serialized_end=313
  _globals['_SESSIONLIST']._serialized_start=316
  _globals['_SESSIONLIST']._serialized_end=473
# @@protoc_insertion_point(module_scope)
