# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/digitalocean/digitaloceanfirewall/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/digitalocean/digitaloceanfirewall/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQproject/planton/provider/digitalocean/digitaloceanfirewall/v1/stack_outputs.proto\x12=project.planton.provider.digitalocean.digitaloceanfirewall.v1\"C\n DigitalOceanFirewallStackOutputs\x12\x1f\n\x0b\x66irewall_id\x18\x01 \x01(\tR\nfirewallIdB\xf1\x02\nAcom.project.planton.provider.digitalocean.digitaloceanfirewall.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPDD\xaa\x02=Project.Planton.Provider.Digitalocean.Digitaloceanfirewall.V1\xca\x02=Project\\Planton\\Provider\\Digitalocean\\Digitaloceanfirewall\\V1\xe2\x02IProject\\Planton\\Provider\\Digitalocean\\Digitaloceanfirewall\\V1\\GPBMetadata\xea\x02\x42Project::Planton::Provider::Digitalocean::Digitaloceanfirewall::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.digitalocean.digitaloceanfirewall.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nAcom.project.planton.provider.digitalocean.digitaloceanfirewall.v1B\021StackOutputsProtoP\001\242\002\005PPPDD\252\002=Project.Planton.Provider.Digitalocean.Digitaloceanfirewall.V1\312\002=Project\\Planton\\Provider\\Digitalocean\\Digitaloceanfirewall\\V1\342\002IProject\\Planton\\Provider\\Digitalocean\\Digitaloceanfirewall\\V1\\GPBMetadata\352\002BProject::Planton::Provider::Digitalocean::Digitaloceanfirewall::V1'
  _globals['_DIGITALOCEANFIREWALLSTACKOUTPUTS']._serialized_start=148
  _globals['_DIGITALOCEANFIREWALLSTACKOUTPUTS']._serialized_end=215
# @@protoc_insertion_point(module_scope)
