# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/iacmodule/v1/pulumi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/iacmodule/v1/pulumi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.connect.pulumibackendcredential.v1 import backend_pb2 as cloud_dot_planton_dot_apis_dot_connect_dot_pulumibackendcredential_dot_v1_dot_backend__pb2
from cloud.planton.apis.infrahub.iacmodule.v1 import git_repo_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_iacmodule_dot_v1_dot_git__repo__pb2
from project.planton.shared.iac.pulumi import pulumi_pb2 as project_dot_planton_dot_shared_dot_iac_dot_pulumi_dot_pulumi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cloud/planton/apis/infrahub/iacmodule/v1/pulumi.proto\x12(cloud.planton.apis.infrahub.iacmodule.v1\x1a\x43\x63loud/planton/apis/connect/pulumibackendcredential/v1/backend.proto\x1a\x37\x63loud/planton/apis/infrahub/iacmodule/v1/git_repo.proto\x1a.project/planton/shared/iac/pulumi/pulumi.proto\"\x86\x01\n\x14PulumiStackOperation\x12T\n\toperation\x18\x01 \x01(\x0e\x32\x36.project.planton.shared.iac.pulumi.PulumiOperationTypeR\toperation\x12\x18\n\x07preview\x18\x02 \x01(\x08R\x07preview\"}\n\rPulumiProject\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12X\n\x07runtime\x18\x02 \x01(\x0e\x32>.cloud.planton.apis.infrahub.iacmodule.v1.PulumiProjectRuntimeR\x07runtime\"\xb3\x03\n\x0fPulumiStackInfo\x12^\n\noperations\x18\x01 \x03(\x0b\x32>.cloud.planton.apis.infrahub.iacmodule.v1.PulumiStackOperationR\noperations\x12^\n\x07\x62\x61\x63kend\x18\x02 \x01(\x0b\x32\x44.cloud.planton.apis.connect.pulumibackendcredential.v1.PulumiBackendR\x07\x62\x61\x63kend\x12Q\n\x07project\x18\x03 \x01(\x0b\x32\x37.cloud.planton.apis.infrahub.iacmodule.v1.PulumiProjectR\x07project\x12\x1d\n\nstack_name\x18\x04 \x01(\tR\tstackName\x12\x1d\n\nstack_fqdn\x18\x05 \x01(\tR\tstackFqdn\x12O\n\x08git_repo\x18\x06 \x01(\x0b\x32\x34.cloud.planton.apis.infrahub.iacmodule.v1.IacGitRepoR\x07gitRepo*~\n\x14PulumiProjectRuntime\x12&\n\"pulumi_project_runtime_unspecified\x10\x00\x12\n\n\x06nodejs\x10\x01\x12\n\n\x06python\x10\x02\x12\x06\n\x02go\x10\x03\x12\n\n\x06\x64otnet\x10\x04\x12\x08\n\x04java\x10\x05\x12\x08\n\x04yaml\x10\x06\x42\x82\x02\n,com.cloud.planton.apis.infrahub.iacmodule.v1B\x0bPulumiProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02(Cloud.Planton.Apis.Infrahub.Iacmodule.V1\xca\x02(Cloud\\Planton\\Apis\\Infrahub\\Iacmodule\\V1\xe2\x02\x34\x43loud\\Planton\\Apis\\Infrahub\\Iacmodule\\V1\\GPBMetadata\xea\x02-Cloud::Planton::Apis::Infrahub::Iacmodule::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.iacmodule.v1.pulumi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.cloud.planton.apis.infrahub.iacmodule.v1B\013PulumiProtoP\001\242\002\005CPAII\252\002(Cloud.Planton.Apis.Infrahub.Iacmodule.V1\312\002(Cloud\\Planton\\Apis\\Infrahub\\Iacmodule\\V1\342\0024Cloud\\Planton\\Apis\\Infrahub\\Iacmodule\\V1\\GPBMetadata\352\002-Cloud::Planton::Apis::Infrahub::Iacmodule::V1'
  _globals['_PULUMIPROJECTRUNTIME']._serialized_start=975
  _globals['_PULUMIPROJECTRUNTIME']._serialized_end=1101
  _globals['_PULUMISTACKOPERATION']._serialized_start=274
  _globals['_PULUMISTACKOPERATION']._serialized_end=408
  _globals['_PULUMIPROJECT']._serialized_start=410
  _globals['_PULUMIPROJECT']._serialized_end=535
  _globals['_PULUMISTACKINFO']._serialized_start=538
  _globals['_PULUMISTACKINFO']._serialized_end=973
# @@protoc_insertion_point(module_scope)
