# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/infrahub/infrapipeline/v1/temporal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/infrahub/infrapipeline/v1/temporal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.infrahub.infrapipeline.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_infrapipeline_dot_v1_dot_api__pb2
from cloud.planton.apis.infrahub.infraproject.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_infrahub_dot_infraproject_dot_v1_dot_api__pb2
from cloud.planton.apis.integration.vcs import git_commit_pb2 as cloud_dot_planton_dot_apis_dot_integration_dot_vcs_dot_git__commit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cloud/planton/apis/infrahub/infrapipeline/v1/temporal.proto\x12,cloud.planton.apis.infrahub.infrapipeline.v1\x1a\x36\x63loud/planton/apis/infrahub/infrapipeline/v1/api.proto\x1a\x35\x63loud/planton/apis/infrahub/infraproject/v1/api.proto\x1a\x33\x63loud/planton/apis/integration/vcs/git_commit.proto\"\xd2\x01\n\"InfraPipelineCreationWorkflowInput\x12^\n\rinfra_project\x18\x01 \x01(\x0b\x32\x39.cloud.planton.apis.infrahub.infraproject.v1.InfraProjectR\x0cinfraProject\x12L\n\ngit_commit\x18\x02 \x01(\x0b\x32-.cloud.planton.apis.integration.vcs.GitCommitR\tgitCommit\"\xea\x01\n$InfraPipelineBuildStageWorkflowInput\x12^\n\rinfra_project\x18\x01 \x01(\x0b\x32\x39.cloud.planton.apis.infrahub.infraproject.v1.InfraProjectR\x0cinfraProject\x12\x62\n\x0einfra_pipeline\x18\x02 \x01(\x0b\x32;.cloud.planton.apis.infrahub.infrapipeline.v1.InfraPipelineR\rinfraPipeline\"\xeb\x01\n%InfraPipelineDeployStageWorkflowInput\x12^\n\rinfra_project\x18\x01 \x01(\x0b\x32\x39.cloud.planton.apis.infrahub.infraproject.v1.InfraProjectR\x0cinfraProject\x12\x62\n\x0einfra_pipeline\x18\x02 \x01(\x0b\x32;.cloud.planton.apis.infrahub.infrapipeline.v1.InfraPipelineR\rinfraPipelineB\x98\x02\n0com.cloud.planton.apis.infrahub.infrapipeline.v1B\rTemporalProtoP\x01\xa2\x02\x05\x43PAII\xaa\x02,Cloud.Planton.Apis.Infrahub.Infrapipeline.V1\xca\x02,Cloud\\Planton\\Apis\\Infrahub\\Infrapipeline\\V1\xe2\x02\x38\x43loud\\Planton\\Apis\\Infrahub\\Infrapipeline\\V1\\GPBMetadata\xea\x02\x31\x43loud::Planton::Apis::Infrahub::Infrapipeline::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.infrahub.infrapipeline.v1.temporal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.cloud.planton.apis.infrahub.infrapipeline.v1B\rTemporalProtoP\001\242\002\005CPAII\252\002,Cloud.Planton.Apis.Infrahub.Infrapipeline.V1\312\002,Cloud\\Planton\\Apis\\Infrahub\\Infrapipeline\\V1\342\0028Cloud\\Planton\\Apis\\Infrahub\\Infrapipeline\\V1\\GPBMetadata\352\0021Cloud::Planton::Apis::Infrahub::Infrapipeline::V1'
  _globals['_INFRAPIPELINECREATIONWORKFLOWINPUT']._serialized_start=274
  _globals['_INFRAPIPELINECREATIONWORKFLOWINPUT']._serialized_end=484
  _globals['_INFRAPIPELINEBUILDSTAGEWORKFLOWINPUT']._serialized_start=487
  _globals['_INFRAPIPELINEBUILDSTAGEWORKFLOWINPUT']._serialized_end=721
  _globals['_INFRAPIPELINEDEPLOYSTAGEWORKFLOWINPUT']._serialized_start=724
  _globals['_INFRAPIPELINEDEPLOYSTAGEWORKFLOWINPUT']._serialized_end=959
# @@protoc_insertion_point(module_scope)
