# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/civo/civokubernetesnodepool/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/civo/civokubernetesnodepool/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from project.planton.shared.foreignkey.v1 import foreign_key_pb2 as project_dot_planton_dot_shared_dot_foreignkey_dot_v1_dot_foreign__key__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBproject/planton/provider/civo/civokubernetesnodepool/v1/spec.proto\x12\x37project.planton.provider.civo.civokubernetesnodepool.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x36project/planton/shared/foreignkey/v1/foreign_key.proto\"\xee\x02\n\x1a\x43ivoKubernetesNodePoolSpec\x12,\n\x0enode_pool_name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x0cnodePoolName\x12n\n\x07\x63luster\x18\x02 \x01(\x0b\x32\x36.project.planton.shared.foreignkey.v1.StringValueOrRefB\x1c\xbaH\x03\xc8\x01\x01\x88\xd4\x61\xe3\x0b\x92\xd4\x61\rmetadata.nameR\x07\x63luster\x12\x1a\n\x04size\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04size\x12)\n\nnode_count\x18\x04 \x01(\rB\n\xbaH\x07*\x02 \x00\xc8\x01\x01R\tnodeCount\x12\x1d\n\nauto_scale\x18\x05 \x01(\x08R\tautoScale\x12\x1b\n\tmin_nodes\x18\x06 \x01(\rR\x08minNodes\x12\x1b\n\tmax_nodes\x18\x07 \x01(\rR\x08maxNodes\x12\x12\n\x04tags\x18\x08 \x03(\tR\x04tagsB\xcb\x02\n;com.project.planton.provider.civo.civokubernetesnodepool.v1B\tSpecProtoP\x01\xa2\x02\x05PPPCC\xaa\x02\x37Project.Planton.Provider.Civo.Civokubernetesnodepool.V1\xca\x02\x37Project\\Planton\\Provider\\Civo\\Civokubernetesnodepool\\V1\xe2\x02\x43Project\\Planton\\Provider\\Civo\\Civokubernetesnodepool\\V1\\GPBMetadata\xea\x02<Project::Planton::Provider::Civo::Civokubernetesnodepool::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.civo.civokubernetesnodepool.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n;com.project.planton.provider.civo.civokubernetesnodepool.v1B\tSpecProtoP\001\242\002\005PPPCC\252\0027Project.Planton.Provider.Civo.Civokubernetesnodepool.V1\312\0027Project\\Planton\\Provider\\Civo\\Civokubernetesnodepool\\V1\342\002CProject\\Planton\\Provider\\Civo\\Civokubernetesnodepool\\V1\\GPBMetadata\352\002<Project::Planton::Provider::Civo::Civokubernetesnodepool::V1'
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['node_pool_name']._loaded_options = None
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['node_pool_name']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['cluster']._loaded_options = None
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['cluster']._serialized_options = b'\272H\003\310\001\001\210\324a\343\013\222\324a\rmetadata.name'
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['size']._loaded_options = None
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['size']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['node_count']._loaded_options = None
  _globals['_CIVOKUBERNETESNODEPOOLSPEC'].fields_by_name['node_count']._serialized_options = b'\272H\007*\002 \000\310\001\001'
  _globals['_CIVOKUBERNETESNODEPOOLSPEC']._serialized_start=213
  _globals['_CIVOKUBERNETESNODEPOOLSPEC']._serialized_end=579
# @@protoc_insertion_point(module_scope)
