# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/gcp/gcpgcsbucket/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/gcp/gcpgcsbucket/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@project/planton/provider/gcp/gcpgcsbucket/v1/stack_outputs.proto\x12,project.planton.provider.gcp.gcpgcsbucket.v1\"7\n\x18GcpGcsBucketStackOutputs\x12\x1b\n\tbucket_id\x18\x01 \x01(\tR\x08\x62ucketIdB\x9c\x02\n0com.project.planton.provider.gcp.gcpgcsbucket.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPGG\xaa\x02,Project.Planton.Provider.Gcp.Gcpgcsbucket.V1\xca\x02,Project\\Planton\\Provider\\Gcp\\Gcpgcsbucket\\V1\xe2\x02\x38Project\\Planton\\Provider\\Gcp\\Gcpgcsbucket\\V1\\GPBMetadata\xea\x02\x31Project::Planton::Provider::Gcp::Gcpgcsbucket::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.gcp.gcpgcsbucket.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.project.planton.provider.gcp.gcpgcsbucket.v1B\021StackOutputsProtoP\001\242\002\005PPPGG\252\002,Project.Planton.Provider.Gcp.Gcpgcsbucket.V1\312\002,Project\\Planton\\Provider\\Gcp\\Gcpgcsbucket\\V1\342\0028Project\\Planton\\Provider\\Gcp\\Gcpgcsbucket\\V1\\GPBMetadata\352\0021Project::Planton::Provider::Gcp::Gcpgcsbucket::V1'
  _globals['_GCPGCSBUCKETSTACKOUTPUTS']._serialized_start=114
  _globals['_GCPGCSBUCKETSTACKOUTPUTS']._serialized_end=169
# @@protoc_insertion_point(module_scope)
