# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/billing/billingaccount/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/billing/billingaccount/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.billing.billingaccount.v1 import enum_pb2 as cloud_dot_planton_dot_apis_dot_billing_dot_billingaccount_dot_v1_dot_enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5cloud/planton/apis/billing/billingaccount/v1/io.proto\x12,cloud.planton.apis.billing.billingaccount.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x37\x63loud/planton/apis/billing/billingaccount/v1/enum.proto\"\xa2\x01\n\x11SubscriptionInput\x12\x18\n\x03org\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03org\x12s\n\x11subscription_plan\x18\x02 \x01(\x0e\x32>.cloud.planton.apis.billing.billingaccount.v1.SubscriptionPlanB\x06\xbaH\x03\xc8\x01\x01R\x10subscriptionPlan\"/\n\x13\x42illingNotification\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"7\n\x17\x42illingPortalSessionUrl\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"Q\n\x1a\x43heckBillingStatusResponse\x12\x19\n\x08is_valid\x18\x01 \x01(\x08R\x07isValid\x12\x18\n\x07message\x18\x02 \x01(\tR\x07messageB\x92\x02\n0com.cloud.planton.apis.billing.billingaccount.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PABB\xaa\x02,Cloud.Planton.Apis.Billing.Billingaccount.V1\xca\x02,Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\xe2\x02\x38\x43loud\\Planton\\Apis\\Billing\\Billingaccount\\V1\\GPBMetadata\xea\x02\x31\x43loud::Planton::Apis::Billing::Billingaccount::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.billing.billingaccount.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.cloud.planton.apis.billing.billingaccount.v1B\007IoProtoP\001\242\002\005CPABB\252\002,Cloud.Planton.Apis.Billing.Billingaccount.V1\312\002,Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\342\0028Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\\GPBMetadata\352\0021Cloud::Planton::Apis::Billing::Billingaccount::V1'
  _globals['_SUBSCRIPTIONINPUT'].fields_by_name['org']._loaded_options = None
  _globals['_SUBSCRIPTIONINPUT'].fields_by_name['org']._serialized_options = b'\272H\003\310\001\001'
  _globals['_SUBSCRIPTIONINPUT'].fields_by_name['subscription_plan']._loaded_options = None
  _globals['_SUBSCRIPTIONINPUT'].fields_by_name['subscription_plan']._serialized_options = b'\272H\003\310\001\001'
  _globals['_BILLINGPORTALSESSIONURL'].fields_by_name['value']._loaded_options = None
  _globals['_BILLINGPORTALSESSIONURL'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_SUBSCRIPTIONINPUT']._serialized_start=190
  _globals['_SUBSCRIPTIONINPUT']._serialized_end=352
  _globals['_BILLINGNOTIFICATION']._serialized_start=354
  _globals['_BILLINGNOTIFICATION']._serialized_end=401
  _globals['_BILLINGPORTALSESSIONURL']._serialized_start=403
  _globals['_BILLINGPORTALSESSIONURL']._serialized_end=458
  _globals['_CHECKBILLINGSTATUSRESPONSE']._serialized_start=460
  _globals['_CHECKBILLINGSTATUSRESPONSE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
