# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/billing/billingaccount/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/billing/billingaccount/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloud.planton.apis.billing.billingaccount.v1 import enum_pb2 as cloud_dot_planton_dot_apis_dot_billing_dot_billingaccount_dot_v1_dot_enum__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7cloud/planton/apis/billing/billingaccount/v1/spec.proto\x12,cloud.planton.apis.billing.billingaccount.v1\x1a\x37\x63loud/planton/apis/billing/billingaccount/v1/enum.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x05\n\x12\x42illingAccountSpec\x12\x36\n\x17organization_created_by\x18\x01 \x01(\tR\x15organizationCreatedBy\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x1f\n\x0b\x63ustomer_id\x18\x03 \x01(\tR\ncustomerId\x12\'\n\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x12k\n\x11subscription_plan\x18\x05 \x01(\x0e\x32>.cloud.planton.apis.billing.billingaccount.v1.SubscriptionPlanR\x10subscriptionPlan\x12@\n\x0etrial_end_date\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0ctrialEndDate\x12\x46\n is_default_payment_method_exists\x18\x07 \x01(\x08R\x1cisDefaultPaymentMethodExists\x12\x46\n\x11next_billing_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0fnextBillingDate\x12\x34\n\x17is_cancel_at_period_end\x18\t \x01(\x08R\x13isCancelAtPeriodEnd\x12W\n\x1a\x63urrent_billing_start_date\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x17\x63urrentBillingStartDate\x12/\n\x13subscription_status\x18\x0b \x01(\tR\x12subscriptionStatusB\x94\x02\n0com.cloud.planton.apis.billing.billingaccount.v1B\tSpecProtoP\x01\xa2\x02\x05\x43PABB\xaa\x02,Cloud.Planton.Apis.Billing.Billingaccount.V1\xca\x02,Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\xe2\x02\x38\x43loud\\Planton\\Apis\\Billing\\Billingaccount\\V1\\GPBMetadata\xea\x02\x31\x43loud::Planton::Apis::Billing::Billingaccount::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.billing.billingaccount.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.cloud.planton.apis.billing.billingaccount.v1B\tSpecProtoP\001\242\002\005CPABB\252\002,Cloud.Planton.Apis.Billing.Billingaccount.V1\312\002,Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\342\0028Cloud\\Planton\\Apis\\Billing\\Billingaccount\\V1\\GPBMetadata\352\0021Cloud::Planton::Apis::Billing::Billingaccount::V1'
  _globals['_BILLINGACCOUNTSPEC']._serialized_start=196
  _globals['_BILLINGACCOUNTSPEC']._serialized_end=891
# @@protoc_insertion_point(module_scope)
