# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.planton.apis.search.v1.apiresource import io_pb2 as cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_apiresource_dot_io__pb2
from cloud.planton.apis.search.v1.iam import io_pb2 as cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_iam_dot_io__pb2


class IamSearchQueryControllerStub(object):
    """iam search query controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.searchIdentityAccountByEmail = channel.unary_unary(
                '/cloud.planton.apis.search.v1.iam.IamSearchQueryController/searchIdentityAccountByEmail',
                request_serializer=cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_iam_dot_io__pb2.SearchIdentityAccountByEmailInput.SerializeToString,
                response_deserializer=cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_apiresource_dot_io__pb2.ApiResourceSearchRecordList.FromString,
                _registered_method=True)


class IamSearchQueryControllerServicer(object):
    """iam search query controller
    """

    def searchIdentityAccountByEmail(self, request, context):
        """The `searchIdentityAccountByEmail` RPC service method enables clients to execute a search operation
        based on a specific email within a specified organization's context.
        This method returns a list of identities that match the input search parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IamSearchQueryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'searchIdentityAccountByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.searchIdentityAccountByEmail,
                    request_deserializer=cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_iam_dot_io__pb2.SearchIdentityAccountByEmailInput.FromString,
                    response_serializer=cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_apiresource_dot_io__pb2.ApiResourceSearchRecordList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.planton.apis.search.v1.iam.IamSearchQueryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.planton.apis.search.v1.iam.IamSearchQueryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IamSearchQueryController(object):
    """iam search query controller
    """

    @staticmethod
    def searchIdentityAccountByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.planton.apis.search.v1.iam.IamSearchQueryController/searchIdentityAccountByEmail',
            cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_iam_dot_io__pb2.SearchIdentityAccountByEmailInput.SerializeToString,
            cloud_dot_planton_dot_apis_dot_search_dot_v1_dot_apiresource_dot_io__pb2.ApiResourceSearchRecordList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
