# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud/planton/apis/servicehub/cookiecuttertemplate/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloud/planton/apis/servicehub/cookiecuttertemplate/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from cloud.planton.apis.servicehub.cookiecuttertemplate.v1 import api_pb2 as cloud_dot_planton_dot_apis_dot_servicehub_dot_cookiecuttertemplate_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>cloud/planton/apis/servicehub/cookiecuttertemplate/v1/io.proto\x12\x35\x63loud.planton.apis.servicehub.cookiecuttertemplate.v1\x1a\x1b\x62uf/validate/validate.proto\x1a?cloud/planton/apis/servicehub/cookiecuttertemplate/v1/api.proto\"6\n\x16\x43ookieCutterTemplateId\x12\x1c\n\x05value\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value\"\xa2\x01\n\x18\x43ookieCutterTemplateList\x12\x1f\n\x0btotal_pages\x18\x01 \x01(\x05R\ntotalPages\x12\x65\n\x07\x65ntries\x18\x02 \x03(\x0b\x32K.cloud.planton.apis.servicehub.cookiecuttertemplate.v1.CookieCutterTemplateR\x07\x65ntriesB\xbf\x02\n9com.cloud.planton.apis.servicehub.cookiecuttertemplate.v1B\x07IoProtoP\x01\xa2\x02\x05\x43PASC\xaa\x02\x35\x43loud.Planton.Apis.Servicehub.Cookiecuttertemplate.V1\xca\x02\x35\x43loud\\Planton\\Apis\\Servicehub\\Cookiecuttertemplate\\V1\xe2\x02\x41\x43loud\\Planton\\Apis\\Servicehub\\Cookiecuttertemplate\\V1\\GPBMetadata\xea\x02:Cloud::Planton::Apis::Servicehub::Cookiecuttertemplate::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud.planton.apis.servicehub.cookiecuttertemplate.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n9com.cloud.planton.apis.servicehub.cookiecuttertemplate.v1B\007IoProtoP\001\242\002\005CPASC\252\0025Cloud.Planton.Apis.Servicehub.Cookiecuttertemplate.V1\312\0025Cloud\\Planton\\Apis\\Servicehub\\Cookiecuttertemplate\\V1\342\002ACloud\\Planton\\Apis\\Servicehub\\Cookiecuttertemplate\\V1\\GPBMetadata\352\002:Cloud::Planton::Apis::Servicehub::Cookiecuttertemplate::V1'
  _globals['_COOKIECUTTERTEMPLATEID'].fields_by_name['value']._loaded_options = None
  _globals['_COOKIECUTTERTEMPLATEID'].fields_by_name['value']._serialized_options = b'\272H\003\310\001\001'
  _globals['_COOKIECUTTERTEMPLATEID']._serialized_start=215
  _globals['_COOKIECUTTERTEMPLATEID']._serialized_end=269
  _globals['_COOKIECUTTERTEMPLATELIST']._serialized_start=272
  _globals['_COOKIECUTTERTEMPLATELIST']._serialized_end=434
# @@protoc_insertion_point(module_scope)
