# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/civo/civodatabase/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/civo/civodatabase/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from project.planton.provider.civo.civodatabase.v1 import spec_pb2 as project_dot_planton_dot_provider_dot_civo_dot_civodatabase_dot_v1_dot_spec__pb2
from project.planton.provider.civo.civodatabase.v1 import stack_outputs_pb2 as project_dot_planton_dot_provider_dot_civo_dot_civodatabase_dot_v1_dot_stack__outputs__pb2
from project.planton.shared import metadata_pb2 as project_dot_planton_dot_shared_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7project/planton/provider/civo/civodatabase/v1/api.proto\x12-project.planton.provider.civo.civodatabase.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x38project/planton/provider/civo/civodatabase/v1/spec.proto\x1a\x41project/planton/provider/civo/civodatabase/v1/stack_outputs.proto\x1a%project/planton/shared/metadata.proto\"\x87\x03\n\x0c\x43ivoDatabase\x12\x43\n\x0b\x61pi_version\x18\x01 \x01(\tB\"\xbaH\x1fr\x1d\n\x1b\x63ivo.project-planton.org/v1R\napiVersion\x12\'\n\x04kind\x18\x02 \x01(\tB\x13\xbaH\x10r\x0e\n\x0c\x43ivoDatabaseR\x04kind\x12Q\n\x08metadata\x18\x03 \x01(\x0b\x32-.project.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\x08metadata\x12[\n\x04spec\x18\x04 \x01(\x0b\x32?.project.planton.provider.civo.civodatabase.v1.CivoDatabaseSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12Y\n\x06status\x18\x05 \x01(\x0b\x32\x41.project.planton.provider.civo.civodatabase.v1.CivoDatabaseStatusR\x06status\"w\n\x12\x43ivoDatabaseStatus\x12\x61\n\x07outputs\x18\x01 \x01(\x0b\x32G.project.planton.provider.civo.civodatabase.v1.CivoDatabaseStackOutputsR\x07outputsB\x98\x02\n1com.project.planton.provider.civo.civodatabase.v1B\x08\x41piProtoP\x01\xa2\x02\x05PPPCC\xaa\x02-Project.Planton.Provider.Civo.Civodatabase.V1\xca\x02-Project\\Planton\\Provider\\Civo\\Civodatabase\\V1\xe2\x02\x39Project\\Planton\\Provider\\Civo\\Civodatabase\\V1\\GPBMetadata\xea\x02\x32Project::Planton::Provider::Civo::Civodatabase::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.civo.civodatabase.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.project.planton.provider.civo.civodatabase.v1B\010ApiProtoP\001\242\002\005PPPCC\252\002-Project.Planton.Provider.Civo.Civodatabase.V1\312\002-Project\\Planton\\Provider\\Civo\\Civodatabase\\V1\342\0029Project\\Planton\\Provider\\Civo\\Civodatabase\\V1\\GPBMetadata\352\0022Project::Planton::Provider::Civo::Civodatabase::V1'
  _globals['_CIVODATABASE'].fields_by_name['api_version']._loaded_options = None
  _globals['_CIVODATABASE'].fields_by_name['api_version']._serialized_options = b'\272H\037r\035\n\033civo.project-planton.org/v1'
  _globals['_CIVODATABASE'].fields_by_name['kind']._loaded_options = None
  _globals['_CIVODATABASE'].fields_by_name['kind']._serialized_options = b'\272H\020r\016\n\014CivoDatabase'
  _globals['_CIVODATABASE'].fields_by_name['metadata']._loaded_options = None
  _globals['_CIVODATABASE'].fields_by_name['metadata']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CIVODATABASE'].fields_by_name['spec']._loaded_options = None
  _globals['_CIVODATABASE'].fields_by_name['spec']._serialized_options = b'\272H\003\310\001\001'
  _globals['_CIVODATABASE']._serialized_start=300
  _globals['_CIVODATABASE']._serialized_end=691
  _globals['_CIVODATABASESTATUS']._serialized_start=693
  _globals['_CIVODATABASESTATUS']._serialized_end=812
# @@protoc_insertion_point(module_scope)
