# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/aws/awssecretsmanager/v1/spec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/aws/awssecretsmanager/v1/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<project/planton/provider/aws/awssecretsmanager/v1/spec.proto\x12\x31project.planton.provider.aws.awssecretsmanager.v1\x1a\x1b\x62uf/validate/validate.proto\"L\n\x15\x41wsSecretsManagerSpec\x12\x33\n\x0csecret_names\x18\x01 \x03(\tB\x10\xbaH\r\x92\x01\n\x08\x01\x18\x01\"\x04r\x02\x10\x01R\x0bsecretNamesB\xad\x02\n5com.project.planton.provider.aws.awssecretsmanager.v1B\tSpecProtoP\x01\xa2\x02\x05PPPAA\xaa\x02\x31Project.Planton.Provider.Aws.Awssecretsmanager.V1\xca\x02\x31Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\xe2\x02=Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\\GPBMetadata\xea\x02\x36Project::Planton::Provider::Aws::Awssecretsmanager::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.aws.awssecretsmanager.v1.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.project.planton.provider.aws.awssecretsmanager.v1B\tSpecProtoP\001\242\002\005PPPAA\252\0021Project.Planton.Provider.Aws.Awssecretsmanager.V1\312\0021Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\342\002=Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\\GPBMetadata\352\0026Project::Planton::Provider::Aws::Awssecretsmanager::V1'
  _globals['_AWSSECRETSMANAGERSPEC'].fields_by_name['secret_names']._loaded_options = None
  _globals['_AWSSECRETSMANAGERSPEC'].fields_by_name['secret_names']._serialized_options = b'\272H\r\222\001\n\010\001\030\001\"\004r\002\020\001'
  _globals['_AWSSECRETSMANAGERSPEC']._serialized_start=144
  _globals['_AWSSECRETSMANAGERSPEC']._serialized_end=220
# @@protoc_insertion_point(module_scope)
