# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project/planton/provider/aws/awssecretsmanager/v1/stack_outputs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project/planton/provider/aws/awssecretsmanager/v1/stack_outputs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEproject/planton/provider/aws/awssecretsmanager/v1/stack_outputs.proto\x12\x31project.planton.provider.aws.awssecretsmanager.v1\"\xeb\x01\n\x1d\x41wsSecretsManagerStackOutputs\x12\x88\x01\n\x0esecret_arn_map\x18\x01 \x03(\x0b\x32\x62.project.planton.provider.aws.awssecretsmanager.v1.AwsSecretsManagerStackOutputs.SecretArnMapEntryR\x0csecretArnMap\x1a?\n\x11SecretArnMapEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xb5\x02\n5com.project.planton.provider.aws.awssecretsmanager.v1B\x11StackOutputsProtoP\x01\xa2\x02\x05PPPAA\xaa\x02\x31Project.Planton.Provider.Aws.Awssecretsmanager.V1\xca\x02\x31Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\xe2\x02=Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\\GPBMetadata\xea\x02\x36Project::Planton::Provider::Aws::Awssecretsmanager::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project.planton.provider.aws.awssecretsmanager.v1.stack_outputs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.project.planton.provider.aws.awssecretsmanager.v1B\021StackOutputsProtoP\001\242\002\005PPPAA\252\0021Project.Planton.Provider.Aws.Awssecretsmanager.V1\312\0021Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\342\002=Project\\Planton\\Provider\\Aws\\Awssecretsmanager\\V1\\GPBMetadata\352\0026Project::Planton::Provider::Aws::Awssecretsmanager::V1'
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS_SECRETARNMAPENTRY']._loaded_options = None
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS_SECRETARNMAPENTRY']._serialized_options = b'8\001'
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS']._serialized_start=125
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS']._serialized_end=360
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS_SECRETARNMAPENTRY']._serialized_start=297
  _globals['_AWSSECRETSMANAGERSTACKOUTPUTS_SECRETARNMAPENTRY']._serialized_end=360
# @@protoc_insertion_point(module_scope)
